### ISSUE TITLE
Bottom of the PromptView wouldn't ba appeared if I use an actionbar theme

### ISSUE THREAD

**Issue by ShayanShojaei** [sjwall/MaterialTapTargetPrompt#10]
Hi
when i turn my application's theme to something not NoActionBar , the bottom of prompt wouldn't be appeared :disappointed: 
Please help me ... :cry: 
it's an emergency :sweat_smile: 
thanks :heart:

**Comment by sjwall** [comment]
Hi

Could you provide more information please?
Are you changing the theme in `styles.xml` or in Java?
What parent themes are you switching between?
What Android version?

Do you mean something like the prompt in the image below where the bottom of the prompt is not rendered?

![screenshot_20160911-220556](https://cloud.githubusercontent.com/assets/16527946/18420590/ce79094a-786d-11e6-8932-c02276ba1ded.png)

**Comment by sjwall** [comment]
Closing as unable to replicate issue without deliberately breaking code and no further details have been provided

**Comment by sjwall** [comment]
Found a similar issue after testing changes in #13

**Comment by sjwall** [comment]
Changes released in v1.4.1
