### ISSUE TITLE
The drawable of the icon is not scaled correctly

### ISSUE THREAD

**Issue by maciaspeter** [sjwall/MaterialTapTargetPrompt#100]
### Overview
 - I implemented the action bar icon to be prompted. The .setIcon() doesn't get the correct resolution of drawable. I verified by checking a same inverted icon and the resolutions are same. 

 - Screenshots 
![screenshot_20180129-143340](https://user-images.githubusercontent.com/8917481/35530257-90f258de-0501-11e8-8677-1454d134f62f.png)

![image](https://user-images.githubusercontent.com/8917481/35530435-09cb9c16-0502-11e8-9976-3c62171904b0.png)

![image](https://user-images.githubusercontent.com/8917481/35530463-1ee78376-0502-11e8-8203-4d5f0b1dee00.png)

 - Stack trace
Nothing

### Reproduction steps

```
new MaterialTapTargetPrompt.Builder(this)
                .setTarget(R.id.screen_option)
                .setIcon(R.drawable.screen_option_default_b)
                .setPrimaryText("Hello World!")
                .setSecondaryText("Don't forget to check the new screen options in the top right corner!")
                .setPromptStateChangeListener(new MaterialTapTargetPrompt.PromptStateChangeListener()
                {
                    @Override
                    public void onPromptStateChanged(MaterialTapTargetPrompt prompt, int state)
                    {

                        switch (state) {
                            case MaterialTapTargetPrompt.STATE_NOT_SHOWN: LogUtils.LOGD(TAG, "STATE_NOT_SHOWN");
                            case MaterialTapTargetPrompt.STATE_REVEALING: LogUtils.LOGD(TAG, "STATE_REVEALING");
                            case MaterialTapTargetPrompt.STATE_REVEALED: LogUtils.LOGD(TAG, "STATE_REVEALED");
                            case MaterialTapTargetPrompt.STATE_FOCAL_PRESSED: LogUtils.LOGD(TAG, "STATE_FOCAL_PRESSED");
                            case MaterialTapTargetPrompt.STATE_FINISHED: LogUtils.LOGD(TAG, "STATE_FINISHED");
                            case MaterialTapTargetPrompt.STATE_DISMISSING: LogUtils.LOGD(TAG, "STATE_DISMISSING");
                            case MaterialTapTargetPrompt.STATE_DISMISSED: LogUtils.LOGD(TAG, "STATE_DISMISSED");
                            case MaterialTapTargetPrompt.STATE_FINISHING: LogUtils.LOGD(TAG, "STATE_FINISHING");
                            case MaterialTapTargetPrompt.STATE_NON_FOCAL_PRESSED: LogUtils.LOGD(TAG, "STATE_NON_FOCAL_PRESSED");

                        }

                        if (state == MaterialTapTargetPrompt.STATE_FOCAL_PRESSED || state == MaterialTapTargetPrompt.STATE_DISMISSED)
                        {
                            //AppPreferences.setGeneralHelpAddNote(this, false);
                        }
                    }
                })
                .show();
```

### Library Version number

    compile 'uk.co.samuelwall:material-tap-target-prompt:2.4.1'

### Operating system and device

Android 7.1 Nougat API 25, Keyone

**Comment by sjwall** [comment]
The library doesn't do any scaling with the drawable icon. All it does to get it is call `activity.getDrawable(resId)`. By the looks of it the app bar does some scaling to the image, I shall investigate this further and see if there is a suitable way to do scaling on the icon in this library

**Comment by prmacias** [comment]
Thank you for checking this issue.  The wayaround solution is to have style to change the background and focal color. Is there a quick guide where I can add some common requests/how-to-dos?

```
<style name="MaterialTapTargetPromptTheme.FabTarget" parent="MaterialTapTargetPromptTheme">
        <item name="mttp_backgroundColour">@color/teal_FF80CBC4</item>
        <item name="mttp_focalColour">@color/black_000000</item>
```

**Comment by sjwall** [comment]
I am improving the documentation here: https://github.com/sjwall/MaterialTapTargetPrompt/tree/documentation/docs

It's a work in-progress and I am not quite sure what it will look like at the end but if you can add a markdown FAQ file with an explanation on how to do it that would be great!
