### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by Maxxan** [sjwall/MaterialTapTargetPrompt#101]
A lot of android 4 users gets UnsupportedOperationException on this line:
uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$PromptView.onDraw (MaterialTapTargetPrompt.java:719)

Using version 2.6.0

**Comment by sjwall** [comment]
This crash is caused by clipping to path with hardware acceleration not being supported in Android SDK < 18. I have disabled hardware acceleration for the library below SDK 18 which solves the issues.

This change has been released in v2.6.1
