### ISSUE TITLE
Can we add time. so it should automatically finish after some interval?

### ISSUE THREAD

**Issue by tarunmehta-quovantis** [sjwall/MaterialTapTargetPrompt#102]

**Comment by sjwall** [comment]
Hi, thanks for the suggestion. I shall look into implementing it in the next release

**Comment by sjwall** [comment]
This has been implemented in e2185e7e51ed1dfb0b24dbe344a900440f0685a9 and released in v2.7.0

Use the `builder.showFor` method ([JavaDoc](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#showFor-long-)), an example is available [here](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/MainActivity.java#L141)
