### ISSUE TITLE
dismiss coachmarks

### ISSUE THREAD

**Issue by MahdiTaghipour** [sjwall/MaterialTapTargetPrompt#103]
### Overview
Hi
In my activity i have implemented about 7 coach marks. i want to know if it is possible to dismiss a showing coach mark when the activity pauses? i should say that it is not clear  which coach mark is open at the moment and i need to dismiss an instance of coach mark.
thanks in advance.

### Library Version number
 -2.3.0

**Comment by sjwall** [comment]
One option is to assign the prompt when it is created to a local variable, when it is dismissed set the local variable to null and then in the `onPause` check if the prompt is null, if it isn't then dismiss it.

```java
private MaterialTapTargetPrompt thePrompt = null;

...

private void showPrompt()
{
     this.thePrompt = new MaterialTapTargetPrompt.Builder(this)
...
        .setPromptStateChangeListener(new MaterialTapTargetPrompt.PromptStateChangeListener()
        {
            @Override
            public void onPromptStateChanged(MaterialTapTargetPrompt prompt, int state)
            {
                if (state == MaterialTapTargetPrompt.STATE_DISMISSED
                    || state == MaterialTapTargetPrompt.STATE_FINISHED)
                {
                    thePrompt = null;
                }
            }
        })
        .create();
    this.thePrompt.show()
}

@Override
public void onPause()
{
    if (this.thePrompt != null)
    {
        this.thePrompt.dismiss();
    }
} 
```

Let me know if this solves it for you
