### ISSUE TITLE
more than 2 prompTargets

### ISSUE THREAD

**Issue by suyashm002** [sjwall/MaterialTapTargetPrompt#104]
### Overview
I am trying to show targets one after another .When user see first promptTarget and dismiss() it then 2nd promptTarget should be shown for this setOnHideListener not working 

### Library Version number

     compile 'uk.co.samuelwall:material-tap-target-prompt:2.6.1'

**Comment by sjwall** [comment]
The `OnHidePromptListener` interface was removed in `v2.0.0` and replaced with the `PromptStateChangeListener` interface. This interface can be used like so:

```java
builder.setPromptStateChangeListener(new MaterialTapTargetPrompt.PromptStateChangeListener()
        {
            @Override
            public void onPromptStateChanged(MaterialTapTargetPrompt prompt, int state)
            {
                if (state == MaterialTapTargetPrompt.STATE_FINISHED 
                    || state == MaterialTapTargetPrompt.STATE_DISMISSED)
                {
                    // Show the next prompt here
                }
            }
        })
```

Please reopen this issue if the above doesn't solve it for you
