### ISSUE TITLE
Unable to get frame for UIBarButtonItem

### ISSUE THREAD

**Issue by maryjudit** [sjwall/MaterialTapTargetPrompt#105]
I'm trying to show target for an app which contains UIBarButtonItems. And getTargetView method crashes when trying to get frame for an UIBarButtonItem. I tried to return `barButtonItem.value(forKey: "view") as! UIView`. It works in real iPad device iOS 9.3. But its not working in latest iOS versions.

**Comment by sjwall** [comment]
How are you running this library on iOS?
I am not sure what help I can be as this library is only designed for and test on Android.

What crash is occurring when `getTargetView` is called? The method only returns a variable so there isn't really anything there that could cause it to crash

**Comment by maryjudit** [comment]
Sorry yaar...i used tap target for ios and finally i got solution..anyway thanks. 👍
