### ISSUE TITLE
it's not dismissing in fragment.

### ISSUE THREAD

**Issue by aqsashahid123** [sjwall/MaterialTapTargetPrompt#107]
### Overview
 - Context, problem or idea, solution or next step
 - Screenshots (if possible)
 - Stack trace (if possible)
 - Is a view not in core Android being targeted, such as the Android Support libraries, if so what version of that library.

### Reproduction steps

 - Detailed steps to reproduce, how is the Builder being created?

### Library Version number

 - e.g. 1.9.0

### Operating system and device

 - e.g. Android 7.1 Nougat API 25, Google Pixel

**Comment by sjwall** [comment]
Could you provide more information please? (as per the issue template...)
I have tested it against v2.7.0 on Android API 26 and it works fine for me in a fragement

**Comment by sjwall** [comment]
Please reopen this with more information if the issue still occurs
