### ISSUE TITLE
Hide prompt programmaticaly

### ISSUE THREAD

**Issue by soad130** [sjwall/MaterialTapTargetPrompt#11]
Hello again =)) and again , this library is awesome. Thank you =)) 

I was wondering if there is any way to close the prompt by java code?

**Comment by sjwall** [comment]
Hi

When calling `create` or `show` from the `Builder` it returns an instance of `MaterialTapTargetPrompt` which has the methods `finish` and `dismiss`.

The `finish` and `dismiss` methods will close the prompt.

See the JavaDocs for reference [here](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.html#finish())
