### ISSUE TITLE
Cannot Resolve v4.Fragment Builder Constructor

### ISSUE THREAD

**Issue by ispam** [sjwall/MaterialTapTargetPrompt#110]
### Overview
I am using **MaterialTapTargetPrompt** on my **HomeActivity** fine with the Navigation Drawer. But when trying to recreate it with a _Spinner_ inside my **HomeFragment** it doesnt allow me to construct?
```
public class HomeFragment extends Fragment {

@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) { 
 View view = inflater.inflate(R.layout.fragment_home, container, false);
 mSpinner = view.findViewById(R.id.spinner_home);

new MaterialTapTargetPrompt.Builder(HomeFragment.this) <--- Cannot resolve constructor 'Builder(package.Fragments)' 
                .setTarget(mSpinner)
                .setPrimaryText("Menú Desplegable")
                .setSecondaryText("Aqui puede seleccionar las diferentes jornadas del torneo!!")
                .setPromptBackground(new FullscreenPromptBackground())
                .setPromptFocal(new RectanglePromptFocal()).show();

return view;
}
```

### Library Version number

 - **2.7**

**Comment by sjwall** [comment]
The library doesn't include the android support library as a dependency so there isn't a constructor in the builder available for the support fragment.
Supply the fragments activity to the builder instead like so:
`new MaterialTapTargetPrompt.Builder(HomeFragment.this.getActivity())`

Please reopen the issue if this doesn't solve it for you
