### ISSUE TITLE
Improvement: Ability to change Font Family

### ISSUE THREAD

**Issue by cnnranderson** [sjwall/MaterialTapTargetPrompt#117]
Feature/Improvement: Ability to change **font family**

It would be great if we could apply a custom font family to the prompt! Probably wouldn't be too difficult I imagine. I tried to override the right values in my app theme, but they don't seem to load up with the prompt.

**Comment by sjwall** [comment]
I believe what you are after is setting the typeface, something like below:

```java
Typeface font = Typeface.createFromAsset(getContext().getAssets(), "robotobold.ttf");
builder.setPrimaryTextTypeface(font, Typeface.NORMAL);
```

Please reopen this issue if it doesn't solve it for you

**Comment by mjalijani** [comment]
it change the PrimaryText font family SecondaryText not !
