### ISSUE TITLE
Incorrect handling big targets

### ISSUE THREAD

**Issue by Dem0n13** [sjwall/MaterialTapTargetPrompt#119]
### Overview

I want to show tip for last item in ListView, but it is shown in front of Prompt:

![gsznamnorkg](https://user-images.githubusercontent.com/1087430/40305541-9acb5bc6-5d03-11e8-8e5b-636f83420b4b.jpg)

I expect of clipping my target.

### Reproduction steps
```
// get bubble in last ListView item
ListView lvDialog = findViewById(R.id.lvDialog);
lvDialog.post(() -> {
    View lastChild = lvDialog.getChildAt(lvDialog.getChildCount() - 1);
    View flBubble = lastChild.findViewById(R.id.flBubble);
    showTip(this, flBubble);
});

// ...
new MaterialTapTargetPrompt.Builder(activity)
    .setTarget(target) // target is flBubble
    .setPrimaryText(titleResId)
    .setSecondaryText(textResId)
    .setCaptureTouchEventOutsidePrompt(true)
    .setPromptStateChangeListener((prompt, state) -> {
        // Console.log(state);
    })
    .show();
```

### Library Version number
1.9.0

### Operating system and device
AVD API 15

**Comment by sjwall** [comment]
For a rectangle shaped target view a `RectanglePromptFocal` can be used [like so](https://github.com/sjwall/MaterialTapTargetPrompt/blob/52641d9ef7188290d25c8982091677fd537892fd/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/MainActivity.java#L250):

```java
import uk.co.samuelwall.materialtaptargetprompt.extras.focals.RectanglePromptFocal;

builder. setPromptFocal(new RectanglePromptFocal())
```

For a circle focal the white area size is not calculated and can be changed by calling `setFocalRadius`:
```java
builder.setFocalRadius(R.dimen.focal_radius);
// or
builder.setFocalRadius(80f);
```

Please reopen this if either of the above does not solve the issue you are seeing

**Comment by Dem0n13** [comment]
I am not about calculation, I am about bug on the screenshot - my bubble is in front of blue big circle, but I except that it will be behind. Please, reopen the issue, I havn't rights.

**Comment by sjwall** [comment]
Are you after the white area being transparent so that the blue area wraps around the target? This can be done with `builder.setFocalColour(Colorado.TRANSPARENT);`

**Comment by sjwall** [comment]
Hi @Dem0n13 
The prompt is drawn on top of all other views apart from the target view which is drawn on top of the prompt. What is displayed as the target can be changed by calling `builder.setTargetRenderView(View)` which will draw the supplied view instead or by calling `builder.setIconDrawable(Drawable)` which will draw the supplied icon instead. Rereading your comment again I think that maybe supplying a transparent icon to `setIconDrawable` might be what you're after
Let me know if you need any more help and I'll reopen this :)
