### ISSUE TITLE
the target prompt is not called in the onCreateView of a fragment

### ISSUE THREAD

**Issue by kevega** [sjwall/MaterialTapTargetPrompt#121]
### Overview
 - in my fragment does not load the target prompt at the beginning, it only does it in the onresume.
 - Screenshots (if possible)
 - Stack trace (if possible)
 - Is a view not in core Android being targeted, such as the Android Support libraries, if so what version of that library.

### Reproduction steps

 - Detailed steps to reproduce, how is the Builder being created?

### Library Version number

 implementation 'uk.co.samuelwall:material-tap-target-prompt:2.9.0'

### Operating system and device

 - e.g. Android 6 API 23, Samsung J7

**Comment by kevega** [comment]
in my fragment does not load the target prompt at the beginning, it only does it in the onresume.

**Comment by sjwall** [comment]
Wrapping the show call in a post to `Handler` like below should make it work:

```java
new android.os.Handler(Looper.getMainLooper()).post(new Runnable()
    {
        @Override
        public void run()
        {
            builder.show()
        }
    });
```

Let me know if this works and I'll add it into the library

**Comment by kevega** [comment]
it did not work,my code is like this:
public class ItemOneFragmentInicio extends Fragment{
public static ItemOneFragmentInicio newInstance() {
        ItemOneFragmentInicio fragment = new ItemOneFragmentInicio();
        return fragment;
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_item_one, container, false);
    }
@Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        setHasOptionsMenu(true);
//some code
new android.os.Handler(Looper.getMainLooper()).post(new Runnable() {
                @Override
                public void run() {
                    View view = getActivity().findViewById(R.id.txt1);
                    showNoAutoDismiss(view);
                }
            });
}
public void showNoAutoDismiss(View view) {
        if (mFabPrompt != null){
            return;
        }
        mFabPrompt = new MaterialTapTargetPrompt.Builder(this)
                .setIcon(R.drawable.icon)
                .setTarget(R.id.icon)
                .setPrimaryText("Alarm")
                .setSecondaryText("Pulse")
                .setAnimationInterpolator(new FastOutSlowInInterpolator())
                .setAutoDismiss(false)
                .setAutoFinish(false)
                .setCaptureTouchEventOutsidePrompt(true)
                .setPromptStateChangeListener(new MaterialTapTargetPrompt.PromptStateChangeListener() {
                    @Override
                    public void onPromptStateChanged(@NonNull MaterialTapTargetPrompt prompt, int state) {
                        if (state == MaterialTapTargetPrompt.STATE_FOCAL_PRESSED) {
                            prompt.finish();
                            mFabPrompt = null;
                        
                        }
                        else if (state == MaterialTapTargetPrompt.STATE_NON_FOCAL_PRESSED) {
                            mFabPrompt = null;
                        }
                    }
                }).show();
    }
    }

I have a fragment and I want it to start automatically.

**Comment by sjwall** [comment]
Could you check if `mFabPrompt` is null after calling `show()`? 
If it is then it means that target view with id `R.id.icon` could not be found

**Comment by sjwall** [comment]
Let me know if you need any more help with this
