### ISSUE TITLE
Show Prompt Once 

### ISSUE THREAD

**Issue by mjalijani** [sjwall/MaterialTapTargetPrompt#122]
There is any Feature that allows the Prompt to Show it once ? for example after the application installed and being open shows the Prompts but for second time doesn't?  i couldn't find something like this , it's really necessary and it would be good .

**Comment by sjwall** [comment]
This is a feature that has been requested previously in #96 and there is a solution in my [response](https://github.com/sjwall/MaterialTapTargetPrompt/issues/96#issuecomment-353618480) which I may build into the library
Is this what you are after?

**Comment by mjalijani** [comment]
yes , thank you so much
