### ISSUE TITLE
doesn't show Text of Textview when setting Prompt

### ISSUE THREAD

**Issue by mjalijani** [sjwall/MaterialTapTargetPrompt#124]
I have **TextView** in my Fragment and i'm set Target to TextView , when Promp showing the **text** of **TextView** doesn't show .

![device-2018-07-04-121353](https://user-images.githubusercontent.com/21081719/42263695-00cb5190-7f84-11e8-835e-2d521b7fc39c.png)

**Comment by sjwall** [comment]
I have tried reproducing the issue in the sample app but the text is always displaying correctly for me
Could you please provide more information on how the prompt is created and the text views attributes so that I can debug this further?

**Comment by mjalijani** [comment]
i don't know what's the reason exactly when i'm setting text to TextView programmilty it work but if i'm setting text in xml it's not !

**Comment by sjwall** [comment]
Thanks for more information on the issue, I am still unable to reproduce the issue using the sample app in the library 
Can you compare how you are creating your builder against the one created [here](https://github.com/sjwall/MaterialTapTargetPrompt/blob/4db748e7afcc9039a8b8024ab62416c049238a88/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/MainActivity.java#L123) and compare your text view against the one [here](https://github.com/sjwall/MaterialTapTargetPrompt/blob/4db748e7afcc9039a8b8024ab62416c049238a88/sample/src/main/res/layout/content_main.xml#L65)?
Anything that you can identify as different will help me debug this further an understand why the text isn't displaying. Does the text display correctly before the prompt is displayed?

**Comment by sjwall** [comment]
Please let me know if any more help is needed :)
