### ISSUE TITLE
Dismiss Prompt in Other Fragment

### ISSUE THREAD

**Issue by mjalijani** [sjwall/MaterialTapTargetPrompt#125]
I have many Fragments in my Activity when i'm replacing a new Fragment .
In last Fragment the Prompts are still Continue and show them in new Fragment 
Basically they should be dismiss automatically when the Fragment is changed. 

i have write this code in my fragment_one : 
```
   new MaterialTapTargetSequence()
                .addPrompt(
                        new MaterialTapTargetPrompt.Builder(getActivity())
//                                .setPreferenceKey("value_show")
                                .setPrimaryText("اسکنر")
                                .setSecondaryText("با فشردن این قسمت می تونی براحتی QR رو اسکن کنی و دیگه نیاز به پر کردن دستی اطلاعات نیست")
                                .setTarget(btn_sendmoney_qr)
                                .setPromptBackground(new RectanglePromptBackground())
                                .setPromptFocal(new RectanglePromptFocal())
                                .setPrimaryTextTypeface(font)
                                .setSecondaryTextTypeface(font))
                .addPrompt(
                        new MaterialTapTargetPrompt.Builder(getActivity())
//                                .setPreferenceKey("transfer")
                                .setPrimaryText("شماره موبایل / شبا")
                                .setSecondaryText("در این قسمت شماره موبایل یا شماره شبا 24 رقمی بدون IR رو وارد کن")
                                .setTarget(edt_phonenumber)
                                .setPrimaryTextTypeface(font)
                                .setSecondaryTextTypeface(font)
                                .setPromptBackground(new RectanglePromptBackground())
                                .setPromptFocal(new RectanglePromptFocal()))

                .show();
```

then i have button that user when clicked the fragment_two will be replaced : 
```
 ScoreFragment homeFragment = new ScoreFragment();
                fragmentManager.beginTransaction().replace(R.id.frame_container,homeFragment).commit();
```

i  think that i have to able **finish();** the Prompts if i am able how should i do this ?

**Comment by sjwall** [comment]
Looks like I need to add a dismiss/finish call to `MaterialTapTargetSequence` so that the sequence can be abandoned part way through

**Comment by sjwall** [comment]
I have added [finish](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetSequence.html#finish--) and [dismiss](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetSequence.html#dismiss--) to `MaterialTapTargetSequence` in `v2.11.0`. If you make the sequence instance accessible in `ScoreFragment` then `finish` or `dismiss` can be called to remove the prompt from view
