### ISSUE TITLE
Doesn't highlight ImageViews

### ISSUE THREAD

**Issue by John61590** [sjwall/MaterialTapTargetPrompt#128]
**The solution I'd like**
I have attempted to use CirclePromptFocal for an ImageView in a RecyclerView but the circle is not as big as the drawable. I am using setTarget ImageView. I'd like a bug fix / better support for ImageViews.

**alternatives I've considered**
I've tried setIcon but I cannot use it since it requires from the resource folder but this is a dynamic drawable.

**Comment by sjwall** [comment]
The circle radius in CirclePromptFocal is fixed and can be changed by calling [builder.setFocalRadius](https://sjwall.github.io/MaterialTapTargetPrompt/javadocs/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setFocalRadius-float-). I will look at adding an option to allow it to calculate the radius based on a padding around the target

There is [builder.setIconDrawable](https://sjwall.github.io/MaterialTapTargetPrompt/javadocs/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setIconDrawable-android.graphics.drawable.Drawable-) to set the icon as a drawable

**Comment by sjwall** [comment]
Please let me know if any more help is needed :)
