### ISSUE TITLE
Cant target RecyclerView child

### ISSUE THREAD

**Issue by ispam** [sjwall/MaterialTapTargetPrompt#129]
Hello, 
First of all, thanks for your awesome library its really nice!

I dove into the sample document inside the ListActivity to check if I could use it with a RecyclerView but its doesnt really pop.

This is the code im trying to use:

```
MaterialTapTargetPrompt.Builder(this)
                        .setTarget(mRecyclerView.getChildAt(0))
                        .setPrimaryText("Escoge tus 8 Equipos")
                        .setSecondaryText("Eston son los equipos con los que vas a competir por el resto del torneo")
                        .setPromptBackground(RectanglePromptBackground())
                        .setPromptFocal(RectanglePromptFocal())
                        .show() ```

Is RecyclerView supported?

**Comment by sjwall** [comment]
Thanks @ispam 
RecyclerView is supported, there is a code example in [CardActivity](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/CardActivity.java) and is also documented [here](https://sjwall.github.io/MaterialTapTargetPrompt/examples#recycler-view-card)

The main difference to a ListView is that `layoutManager.findViewByPosition(index)` is used to find the view as the View at position 0 with `getChildAt(0)` may not represent the first item in the list adapter. `findViewByPosition` will get the View for the list adapter position, which could be null if not displayed

**Comment by ispam** [comment]
Thanks @sjwall 

I just checked your links but unfortunately im still failing at something? Would you mind guiding me out pls?

**Activity.kt**
```
val card = GridLayoutManager(this, 3).findViewByPosition(0) as android.widget.GridLayout
                    val viewHolder = mRecyclerView.getChildViewHolder(card) as SelectionAdapter.ViewHolder
                    MaterialTapTargetPrompt.Builder(this)
                            .setTarget(viewHolder.mCardView)
                            .setPrimaryText(getString(R.string.prompt_extra1))
                            .setSecondaryText(getString(R.string.prompt_extra2))
                            .setBackgroundColour(resources.getColor(R.color.colorPrimaryDark))
                            .setAnimationInterpolator(FastOutSlowInInterpolator())
                            .setPromptBackground(RectanglePromptBackground())
                            .setPromptFocal(RectanglePromptFocal())
                            .show()
```
**ViewHolder**

```  
 inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view){

 val  mCardView = view.findViewById(R.id.selection_CV) as CardView```

**Error**
`OnErrorNotImplementedException: null cannot be cast to non-null type android.widget.GridLayout`

^ also tried with **import android.support.v7.widget.GridLayout**

**Comment by sjwall** [comment]
Hi @ispam I am happy to guide you, sorry for the delay I have had been quite busy the past few days and not had chance to look till now

It looks findViewByPosition(0) is possibly returning null and card isn't accepting null values
Try changing card to allow null with:

```kotlin
val card? = GridLayoutManager(this, 3).findViewByPosition(0) as android.widget.GridLayout
```
It is also worth checking in the ViewHolder layout xml whether it is using the android GridLayout or the support library as there are questions on stackoverflow where this was an issue

**Comment by sjwall** [comment]
Please let me know if any more help is needed :)
