### ISSUE TITLE
White space on top

### ISSUE THREAD

**Issue by zuck-ale** [sjwall/MaterialTapTargetPrompt#13]
Thanks for your awesome library...
I use this in a device without the status bar (removed by the System), and when I call the function  `new MaterialTapTargetPrompt`  appears on the top a white space (I think is the margin of the status bar).
There's a possibility to remove this space?

Thanks

![device-2016-09-28-170555](https://cloud.githubusercontent.com/assets/5824404/18919383/2f17f2c4-859e-11e6-81e8-df233e369e9d.png)

**Comment by sjwall** [comment]
Yes, the white gap is it thinking that the status bar is there, it gets the height from a system constant. I shall try and improve how it detects if the status bar is there or add a method to disable it.

**Comment by sjwall** [comment]
Changes released in v1.4.1, could you please confirm that these changes fix this issue?

**Comment by zuck-ale** [comment]
Yes, it works perfectly.
Thanks for your work
