### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AngleV** [sjwall/MaterialTapTargetPrompt#130]
On some devices i get a NullPointerException

Device : LG-H870
OS : 8

---------------
Device : Redmi Note 3
Os : 6.0.1

Stack Trace
------------------------------------
uk.co.samuelwall.materialtaptargetprompt.ActivityResourceFinder.getResources (ActivityResourceFinder.java:72)
uk.co.samuelwall.materialtaptargetprompt.extras.PromptOptions.<init> (PromptOptions.java:202)
uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init> (MaterialTapTargetPrompt.java:1076)
uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init> (MaterialTapTargetPrompt.java:1060)
uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init> (MaterialTapTargetPrompt.java:1044)

EDIT
I am using v. 2.9.0 of library

**Comment by sjwall** [comment]
From the stack trace it looks like activity is being passed into the builder as `null`
The builder constructor parameter activity is annotated `@NonNull` as an activity is required
Adding a null check for activity before calling the builder constructor should solve this

Let me know if you have any more help on this

**Comment by AngleV** [comment]
@sjwall 
ok i will try it but how is possible for the activity to be null?

i am using the library inside a Fragment and a get the parent activity with the following code

    @Override
    public void onAttach(Context activity) {
        this.activity = (MainActivity.class.isAssignableFrom(activity.getClass())) ? (MainActivity) activity : null;
        super.onAttach(activity);
    }


and later i m calling the builder 

            tapTargetPromptBuilder = new MaterialTapTargetPrompt.Builder(activity)

**Comment by sjwall** [comment]
Going on your code it could be either the call to `isAssignableFrom` in `onAttach` is returning false or the builder creation is called before `onAttach` is called. It is unlikely to be `onAttach` being called after as it is the first call in the fragment lifecycle

**Comment by sjwall** [comment]
Please let me know if any more help is needed :)
