### ISSUE TITLE
Help request: MaterialTapTargetSquence with CustomPromptBuild

### ISSUE THREAD

**Issue by develuxe** [sjwall/MaterialTapTargetPrompt#132]
Hello there,
first of all thanks for this awesome lib!

I'm trying to create a sequence of CustomPromptBuilder prompts. Each prompt should be shown only once.
I've stumbled upon https://github.com/sjwall/MaterialTapTargetPrompt/issues/123 and implemented the CustomPromptBuilder class from https://sjwall.github.io/MaterialTapTargetPrompt/builder
But the CustomPromptBuilder.show() method never gets called thus a shared pref is never stored.

This is my implementation:
```
new MaterialTapTargetSequence()
		.addPrompt(new CustomPromptBuilder(getActivity())
				.setPreferenceKey("onboarding_2")
				.setPrimaryText("text")
				.setSecondaryText("text")
				.setAnimationInterpolator(new FastOutSlowInInterpolator())
				.setTarget(view)
				.setCaptureTouchEventOnFocal(true)
				.setPromptBackground(new RectangleDimmedPromptBackground())
				.setPromptFocal(new RectanglePromptFocal()))
		.addPrompt(new CustomPromptBuilder(getActivity())
				.setPreferenceKey("onboarding_2")
				.setPrimaryText("text")
				.setSecondaryText("text")
				.setAnimationInterpolator(new FastOutSlowInInterpolator())
				.setTarget(view)
				.setCaptureTouchEventOnFocal(true)
				.setPromptBackground(new RectangleDimmedPromptBackground())
				.setPromptFocal(new RectanglePromptFocal()))
		.show();
```

Pretty sure I'm missing something complety obvious :) 
I would appreciate any help! Thanks

**Comment by sjwall** [comment]
Thanks @develuxe 
Going on your code it is most likely the target view not being found
The first thing to try would be to move the first prompt out of the sequence and see if the call to `builder.show()` returns `null`. If it returns `null` then a target is not set or the target view could not be found or both the primary and secondary text are `null`.

If the sequence is being shown from a lifecycle event try wrapping it in the below code so that the prompt is created after the target view is created:
```java
new android.os.Handler(Looper.getMainLooper()).post(new Runnable()
{
    @Override
    public void run()
    {
        // Create the prompt here
    }
})
```

**Comment by develuxe** [comment]
Thanks @sjwall 
The prompts are being shown that's not the problem.
What I try to achieve is that the prompts set a sharedpref key so they won't get shown again a second time. The `show()` method in `CustomPromptBuilder` does not get called.

**Comment by sjwall** [comment]
ohhhhh I see now, `show()` never gets called in the sequence woops
`builder.create()` is called and then `prompt.show()`

Change to override `create()` instead of `show()`, I'll update the example

**Comment by sjwall** [comment]
I have updated the example [here](https://sjwall.github.io/MaterialTapTargetPrompt/builder)
Changes can be seen in commit 94aa5a0
This should solve it

**Comment by develuxe** [comment]
@sjwall Awesome! Works exactly like intended :) Thank you
