### ISSUE TITLE
Please, provide a way to know if the backbutton was pressed.

### ISSUE THREAD

**Issue by aMarCruz** [sjwall/MaterialTapTargetPrompt#138]
**Describe the solution you'd like**
I want to know when the back button dimissed the prompt to stop a sequence.

**Describe alternatives you've considered**
I think in two options:
a) Raise a different event, ex: STATE_BACKBUTTON_PRESSED.
b) Give a additional parameter in the STATE_DISMISSING and/or STATE_DISMISSED event

**Additional context**
n/a

@sjwall and contributors,  thanks for this awesome library!

**Comment by sjwall** [comment]
Thanks for the great suggestion, `STATE_BACK_BUTTON_PRESSED` state has been added and is emitted before `STATE_NON_FOCAL_PRESSED` when the system back button is pressed

This is released in `v2.13.0`

**Comment by aMarCruz** [comment]
@sjwall , thanks!!!
