### ISSUE TITLE
How would we do multi focus ?

### ISSUE THREAD

**Issue by basith0304** [sjwall/MaterialTapTargetPrompt#140]
I just want to do multi focus at the same time .

![screen shot 2018-10-16 at 8 49 25 am](https://user-images.githubusercontent.com/5030406/46995471-96448900-d121-11e8-9a7f-b92c17fd31d9.jpg)
![screen shot 2018-10-16 at 8 49 32 am](https://user-images.githubusercontent.com/5030406/46995473-980e4c80-d121-11e8-94d4-af1f5918a460.jpg)

**Comment by AbdulSamadQureshi** [comment]
Any expected time when this feature will be out?

**Comment by sjwall** [comment]
I will look into this. It will be a case of targeting the parent view to these views and then having a custom [PromptFocal](https://sjwall.github.io/MaterialTapTargetPrompt/javadocs/uk/co/samuelwall/materialtaptargetprompt/extras/PromptFocal.html) which draws around each child view

**Comment by sjwall** [comment]
PR welcome but have no intention to implement this
