### ISSUE TITLE
Target misplaced when used in combination with BottomNavigationView

### ISSUE THREAD

**Issue by alixwar** [sjwall/MaterialTapTargetPrompt#141]
**Describe the bug / To Reproduce**
Difficult to explain so I will add an example:
- A layout with a bottomnavigation view and a coordinator layout that includes the fab (FloatingActionButton)
- Two different bottom navigation options: "A" and "B" (where the fab is shown in "A" but not in "B")
- "B" is active, i.e. fab is hidden
- Navigate to "A" (in BottomNavigationView.OnNavigationItemSelectedListener.onNavigationItemSelected() then show the fab again and create the MaterialTapTargetPrompt targeting the fab)
- As can be seen on the screenshot, the target is not exactly on top of the fab
- Note: When already on "A" and navigating to "A", it works as expected.

**Expected behavior**
The target should be exactly on top of the fab

**Screenshots**
This is where the fab is located:
![screenshot_20181025-094531_access manager](https://user-images.githubusercontent.com/5415786/47484078-21690180-d83b-11e8-96de-2cbbfe7f95c4.jpg)

This shows the problem: The target is not on top of the fab:
![screenshot_20181025-094741_access manager](https://user-images.githubusercontent.com/5415786/47484076-1e6e1100-d83b-11e8-9e33-daa467e9f772.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 8.0
 - Library version 2.13

**Comment by sjwall** [comment]
The only way I have been able to cause a layout issue is when setting `layout_insetEdge` on the FAB which causes the layout issue to always occur. I will continue to investigate and hopefully find a fix for this but it looks like `View.getLocationInWindow` is returning the wrong location when `layout_insetEdge` is used

**Comment by znakeeye** [comment]
This might be related to https://github.com/sjwall/MaterialTapTargetPrompt/issues/171
