### ISSUE TITLE
Disallow touching of views when showing the prompt

### ISSUE THREAD

**Issue by lucky919** [sjwall/MaterialTapTargetPrompt#142]
I am able to touch views beneath the prompt, Is there any way to stop allowing the touch events beneath the prompt ?

**Comment by sjwall** [comment]
To disallow touches use [setCaptureTouchEventOutsidePrompt](https://sjwall.github.io/MaterialTapTargetPrompt/javadocs/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setCaptureTouchEventOutsidePrompt-boolean-) in the builder

```java
builder.setCaptureTouchEventOutsidePrompt(true)
```

There is also [setCaptureTouchEventOnFocal](https://sjwall.github.io/MaterialTapTargetPrompt/javadocs/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setCaptureTouchEventOnFocal-boolean-) that can be used to stop the touch event passing to the target
