### ISSUE TITLE
Showing prompt for ViewHolder in RecyclerView of a child fragment

### ISSUE THREAD

**Issue by ShahoodulHassan** [sjwall/MaterialTapTargetPrompt#144]
Hello,

I want to show a prompt to target a `TextView` in `ViewHolder` of the `RecyclerView` where this `RecyclerView` is in a child fragment. For this, I've set up the prompt in the child fragment passing child fragment to the `builder`. I've able to find the target view correctly. I've checked and it is not null. `PromptStateChangeListener` also tells that the prompt has been 'revealed' BUT still the prompt is not visible on screen.
I have been able to show prompts for `Toolbar` items, FAB and `TextView` in the parent fragment successfully though.

Is it a known issue and is it caused by the implementation being in a child fragment?

Thanks

**Comment by sjwall** [comment]
See [card example](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/CardActivity.java)
