### ISSUE TITLE
Spcae on the Top of view 

### ISSUE THREAD

**Issue by Raghu479** [sjwall/MaterialTapTargetPrompt#151]
**Describe the bug**
A show view is not occupying the total space on the top.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your    @@@problem.

**Stack trace**
If applicable, add the stack trace for the exception thrown to help trace your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel] Pocof1
 - OS: [e.g. Android 7.1 Nougat API 25] Android 8.1
 - Library version [e.g. 2.9.0] 2.14.0

**Additional context**
![screenshot_2019-01-09-18-04-06-349_com reallymake android pottery 1](https://user-images.githubusercontent.com/46526604/50901770-2a7f6d00-143f-11e9-8566-33f5333c5909.png)

**Comment by sjwall** [comment]
Looks like double accounting for the status bar height, this is a configurable option in the latest release so should be fixed
