### ISSUE TITLE
Not Support (v4) Fragment In ViewPager 

### ISSUE THREAD

**Issue by habahbehbassam** [sjwall/MaterialTapTargetPrompt#153]
**Describe the bug**
When Use "new MaterialTapTargetPrompt.Builder(this)" with fragment in viewpager the tutorial not shown ! 

**Smartphone (please complete the following information):**
 - Device: Google Pixel Xl2 , Huawei Nexus 6p
 - OS: Android 9 , Android 8
 - Library version [2.14.0]

**Comment by islavstan** [comment]
use MaterialTapTargetPrompt.Builder(activity) instead MaterialTapTargetPrompt.Builder(fragment)
It helps me
