### ISSUE TITLE
not showing promot for ApppBar items

### ISSUE THREAD

**Issue by MohsenNaderzadeh** [sjwall/MaterialTapTargetPrompt#154]
hi i want to show promot for  navigation menu icon that is in my app bar i use this code in OnCreate Mehtod of Activity : 
        new MaterialTapTargetPrompt.Builder(MainActivity.this)
                .setTarget(R.id.action_navigation)
                .setPrimaryText("Primary text")
                .setIcon(R.drawable.home)
                .show();
but it does not worked and my app does not crash and has not any error 
but when i use above code in onOptionsItemSelected method for click event of action_navigaiton 
above code worked. I want to show promot when user see the activity and for this i think i should write this Code in OnCreateMethod.
for test i use above code for my bottom navigation items and again above code worked but i don't know why it does not worked for my navigation menu icon that is in AppBar

**Comment by KryptKode** [comment]
Have you tried calling in `onResume` or at the end of `onCreateOptionsMenu`? You can also check this. https://sjwall.github.io/MaterialTapTargetPrompt/faq#show-from-a-life-cycle-event

**Comment by miduch** [comment]
also facing similar issue (in my fragment), tried calling at the end of onCreateOptionsMenu and also tried show-from-a-life-cycle-event. No help

mTargetView is always null when id of visible menu item is used. 

PromptOptions.java
    public T setTarget(@IdRes final int target)
    {
        mTargetView = mResourceFinder.findViewById(target);
        mTargetPosition = null;
        mTargetSet = mTargetView != null;
        return (T) this;
    }

**Comment by valibran** [comment]
I had the same problem for menu items inside my fragment. 
I managed to make it work by passing the activity instead of the fragment to the builder and adding everything inside a delayed handler.
```
        Handler().postDelayed({
            MaterialTapTargetPrompt.Builder(requireActivity())
                    .setTarget(R.id.action_search)
                    .setPrimaryText("Primary text")
                    .setCaptureTouchEventOnFocal(true)
                    .setCaptureTouchEventOutsidePrompt(true)
                    .show()
        }, 100) 
```
