### ISSUE TITLE
Do you have "jar" file as a lib?

### ISSUE THREAD

**Issue by mrHelg** [sjwall/MaterialTapTargetPrompt#155]
Hello!

Probably, my question is stupid.....
But I still use jar files as libraries. Do you have one?
Thanks in advance,

**Comment by sjwall** [comment]
An .aar file is available to download from [here](https://bintray.com/sjwall/maven/material-tap-target-prompt/3.0.0#files/uk%2Fco%2Fsamuelwall%2Fmaterial-tap-target-prompt%2F3.0.0) which can be [converted to a jar file](https://stackoverflow.com/questions/21417419/how-to-convert-aar-to-jar) I believe
