### ISSUE TITLE
 grey full screen rectangle   after propmt will appear as shown in figure

### ISSUE THREAD

**Issue by abhishek8506** [sjwall/MaterialTapTargetPrompt#156]
![img_20190225_115215](https://user-images.githubusercontent.com/34652662/53318159-5920ac80-38f4-11e9-9059-c5a957a9c7f6.jpg)

as you see in figure a grey background strip all corner ,appear after prompt,help me ,,
as data should hide  as per app detail thus should .
thanks

**Comment by sjwall** [comment]
Insufficient information to be able to fix
