### ISSUE TITLE
Showing TapTarget on RecyclerView Viewholder

### ISSUE THREAD

**Issue by shaharcarbyne** [sjwall/MaterialTapTargetPrompt#159]
**Describe the bug**
Trying to show a prompt on a view holder, similar to what's done in [https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/ListActivity.java](url)
I can't make it work.
Is it possible showing it for RecyclerView child?

**Comment by NileshJarad** [comment]
Why don't you just pass the `layoutmanger.getChildAt(postition)` as view to function

**Comment by sjwall** [comment]
There is an example here [https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/CardActivity.java#L53](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/CardActivity.java#L53)
