### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by virengujariya** [sjwall/MaterialTapTargetPrompt#162]
**Describe the solution you'd like**
Is library open to accept Pull Requests for `androidx` migration?

**Comment by sjwall** [comment]
It is :)

**Comment by virengujariya** [comment]
@sjwall created pull request https://github.com/sjwall/MaterialTapTargetPrompt/pull/164. Feel free to make suggestions.

**Comment by sjwall** [comment]
#164 closes this in release v3.0.0
