### ISSUE TITLE
Next/SKip button or custom layout 

### ISSUE THREAD

**Issue by AddyArya25** [sjwall/MaterialTapTargetPrompt#163]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AddyArya25** [comment]
I find no way to add Next/Skip button or some layout/view. Please add

**Comment by FaisalFiyyaz** [comment]
> I find no way to add Next/Skip button or some layout/view. Please add

did you find any solution for this. I also want skip button on prompt.
