### ISSUE TITLE
Way to have skip button to skip tutorial

### ISSUE THREAD

**Issue by FaisalFiyyaz** [sjwall/MaterialTapTargetPrompt#165]
I have tutorial demo app and I've successfully implemented it for my app but is there a way to have a skip button on the prompt to skip that tutorial?

**Comment by NewestUser** [comment]
It will be nice to have a skip button.
I have noticed that a lot of my users end up clicking outside of the prompt.

**Comment by sjwall** [comment]
Duplicate of #163
