### ISSUE TITLE
Is there a way to add DimmedPromptBackground() with RectanglePromptBackground()?

### ISSUE THREAD

**Issue by amrita019** [sjwall/MaterialTapTargetPrompt#166]
I wanted to Dim the background but while keeping the prompt background Rectangular in shape.

**Comment by sjwall** [comment]
I guess that you're looking at this https://sjwall.github.io/MaterialTapTargetPrompt/shapes

Should be able to change the parent class to RectanglePromptBackground and it will work the same

```java
public class DimmedPromptBackground extends RectanglePromptBackground
```

**Comment by amrita019** [comment]
Thank you @sjwall!
Also, it's an amazing library. Great work there! :)
