### ISSUE TITLE
Keep prompt open when clicked

### ISSUE THREAD

**Issue by wizlif** [sjwall/MaterialTapTargetPrompt#170]
Is it possible to keep the prompt open when clicked?

I only need to dismiss it programmatically based on a specific condition.

**Comment by sjwall** [comment]
There is [setAutoDismiss(false)](https://sjwall.github.io/MaterialTapTargetPrompt/javadoc/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setAutoDismiss-boolean-) and [setAutoFinish(false)](https://sjwall.github.io/MaterialTapTargetPrompt/javadoc/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setAutoFinish-boolean-) where dismiss is outside the prompt focal/target and finish is anywhere else
