### ISSUE TITLE
Prompt appears under appbar's tab layout?

### ISSUE THREAD

**Issue by znakeeye** [sjwall/MaterialTapTargetPrompt#171]
I have a toolbar with a button I want to highlight:

```java
MaterialTapTargetPrompt.Builder(this)
    .setPrimaryText("Cast")
    .setSecondaryText("Some description")
    .setIconDrawable(drawable)
    .setTarget(button)
    .show();
```

This used to work, but then I added a `TabLayout` below the toolbar. See the layout below. Now, the prompt gets obscured by the tab layout. **How do I make the prompt appear above the tab layout?**

**Note** that I removed the title text. The prompt circle is only visible in the area _below the tab layout_! Sorry if the image is not clear enough.

![image](https://user-images.githubusercontent.com/958469/82713072-00bc9400-9c8a-11ea-9b52-47c3f0875dac.png)

**The Layout**

```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true">

        <!-- Button in toolbar... -->
        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize" />

        <!-- But there is a tab layout as well... -->
        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </com.google.android.material.appbar.AppBarLayout>
    
    <!-- The rest here -->

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Comment by znakeeye** [comment]
This is likely an edge case where `getLocationInWindow` gives the wrong value. See detailed explanation [here](https://stackoverflow.com/questions/17672891/getlocationonscreen-vs-getlocationinwindow).

**Comment by znakeeye** [comment]
A workaround is to change the builder (from within the **fragment**) from:

`MaterialTapTargetPrompt.Builder(this)`
to
`MaterialTapTargetPrompt.Builder(getActivity())`

Any ideas why this could have an effect?

**Comment by sjwall** [comment]
Ah so when a Fragment is supplied to the builder it adds the prompt to [fragment.getView().getParent()](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/SupportFragmentResourceFinder.java#L69) but when you supply an Activity it adds the prompt to [activity.getWindow().getDecorView()](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/ActivityResourceFinder.java#L58)

Using a Fragment the tabs are higher up in the view hierarchy than the Fragment so the prompt will be displayed under it

Let me know if you have any more questions

**Comment by znakeeye** [comment]
I experienced a similar problem when showing a prompt for a BottomSheet header. In this case, the above trick did not work. The prompt is displayed under the header. I tried all views in the hierarchy below. No success. **Ideas?**

```xml
<androidx.core.widget.NestedScrollView
	android:id="@+id/sheet"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:fitsSystemWindows="true"
	app:behavior_hideable="false"
	app:behavior_peekHeight="@dimen/bottom_sheet_peek_height"
	app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">

	<RelativeLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:descendantFocusability="blocksDescendants"
		android:orientation="vertical">

		<FrameLayout
			android:id="@+id/bottom_sheet_header"
			android:layout_width="match_parent"
			android:layout_height="wrap_content">

			<androidx.appcompat.widget.AppCompatTextView
				android:id="@+id/header_view"
				android:layout_width="match_parent"
				android:layout_height="@dimen/bottom_sheet_peek_height"
				android:gravity="center_vertical"
				android:text="Above prompt :(" />
		</FrameLayout>
		
		<!-- Rest of Bottom sheet view -->
	</RelativeLayout>
</androidx.core.widget.NestedScrollView>
```

Then in my fragment I call:

```java
MaterialTapTargetPrompt.Builder(requireActivity()) // Tried "this" as well...
	.setPrimaryText("Foo")
	.setSecondaryText("Bar")
	.setTarget(sheetHeader)
	.show();
```

And the prompt keeps getting displayed under the header...
