### ISSUE TITLE
Tap Target Circle is cut off on Nokia 8.1 with Android 10

### ISSUE THREAD

**Issue by bluesource** [sjwall/MaterialTapTargetPrompt#174]
**Describe the bug**
The feature discovery is cut off when the target is located in the toolbar. This seems only to happen on the Nokia 8.1 device with Android 10. See the attached screenshot for additional info. 
This issue appears in the Material Tap Target Sample app and in our own applications.

**To Reproduce**
Steps to reproduce the behaviour including how the prompt builder is created:
1. Start the Material Tap Target Sample app (installed from playstore)
2. Click on 'NAVIGATION' Button
4. The discovery is shown but it is cut off, see screenshot for more details

**Expected behavior**
The discovery should be displayed correctly and fill the top of the screen.

**Screenshots**
![Screenshot_20200825-112213](https://user-images.githubusercontent.com/3057403/91163762-5dd34600-e6ce-11ea-912e-83a7c37b4a72.png)

**Stack trace**
none

**Smartphone (please complete the following information):**
 - Device: Nokia 8.1
 - OS: Android 10
 - Library version: 3.0.0

**Additional context**
As mentioned above: only observed on Nokia 8.1 with Android 10 and only when the Tap Target is in the toolbar.

**Comment by Alok191196** [comment]
try this it worked for me 
`setClipToView(null)`
