### ISSUE TITLE
setting the Height and width of the Prompt background at run time

### ISSUE THREAD

**Issue by AnuragKataria** [sjwall/MaterialTapTargetPrompt#181]
![s1](https://user-images.githubusercontent.com/12609256/98236724-d46fa800-1f89-11eb-8622-3142baee6c35.png)
I'm struggling to set height of the prompt background at run time. If there is any function which is already available please let me know.

Actually I want to add skip and Next button and I have added both button in my View and I will customise the height of the Prompt background which will make it as the part of Material Prompt.

**Comment by sjwall** [comment]
Hi, you could implement your own [RectanglePromptBackground](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/backgrounds/RectanglePromptBackground.java) and use the call to  `mBaseBounds.set(x1, y1, x2, y2)` in `prepare` to set your desired size
