### ISSUE TITLE
Display multiple prompt target and go them step by step

### ISSUE THREAD

**Issue by mrSOMik** [sjwall/MaterialTapTargetPrompt#184]
Hello!
First of all, thank you for your great library!

I want to display multiple prompt target and go them step by step without interrupting the process by clicking on other views.
So, I added "builder.setCaptureTouchEventOnFocal(true)" as you recomendded above, but the process was still interrupted when clicking on other views and to avoit it I also added ".setCaptureTouchEventOutsidePrompt(true)".

And now what state or states I need to put in "setPromptStateChangeListener" to show the next prompt target on tap anywhere?
Using only "state == MaterialTapTargetPrompt.STATE_DISMISSED" does not work when I tap on focal.
To solve it I added 2 states "state == MaterialTapTargetPrompt.STATE_FOCAL_PRESSED || state == MaterialTapTargetPrompt.STATE_DISMISSED".
Is It correct or is there other simple way?

Thanks in advance.

**Comment by sjwall** [comment]
Hi, you want to use `builder.setAutoDismiss(false)` and handle the dismissing yourself in the prompt events

There is a sequence example [here](https://github.com/sjwall/MaterialTapTargetPrompt/blob/d2449fc590b1ee12dd88e59c04e7237bb2d3bdcb/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/MainActivity.java#L297)
