### ISSUE TITLE
Change opacity of background

### ISSUE THREAD

**Issue by burhankhanzada** [sjwall/MaterialTapTargetPrompt#185]
I wound like to lower the opacity of background how to do that

**Comment by sjwall** [comment]
The background opacity is obtained from the background colour [`mBaseColourAlpha = Color.alpha(colour)`](https://github.com/sjwall/MaterialTapTargetPrompt/blob/d2449fc590b1ee12dd88e59c04e7237bb2d3bdcb/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/backgrounds/RectanglePromptBackground.java#L77)
