### ISSUE TITLE
JCenter shuts down in May

### ISSUE THREAD

**Issue by MihashiHans** [sjwall/MaterialTapTargetPrompt#189]
**Describe the solution you'd like**
Please publish to MavenCentral.

**Describe alternatives you've considered**

**Additional context**
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

https://github.com/sjwall/MaterialTapTargetPrompt/issues/187

**Comment by sjwall** [comment]
I shall look at publishing to MavenCentral

In the mean time the latest few versions are published to Github [here](https://github.com/sjwall?tab=packages&repo_name=MaterialTapTargetPrompt)

JCenter will continue to serve packages until February 1st 2022

**Comment by kevingermainbusiness** [comment]
This library is a game changer for me as an android developer, it helped me so much with explaining my app's UI, I hope you make the switch to mavenCentral as soon as possible 👍

**Comment by sjwall** [comment]
I have raised the ticket to get it published: https://issues.sonatype.org/browse/OSSRH-68344
Will get it published as soon as the repository is created and then close this issue

**Comment by sjwall** [comment]
All versions have been published to maven central

Please let me know if there is an issue
