### ISSUE TITLE
Use Target for ahbottomnavigation

### ISSUE THREAD

**Issue by MansoorJafari** [sjwall/MaterialTapTargetPrompt#19]
Hi
I want use this target for bottomnavigation 
please help that why use it.

Thanks

**Comment by sjwall** [comment]
I shall have a look at it. It will most likely be: searching for the menu item as a child view in the bottom navigation view and then setting the child view as the target

**Comment by nightstorm99** [comment]
bottomNavigation = (AHBottomNavigation) findViewById(R.id.bottom_navigation);
....
.....

tapTargetPromptBuilder.setTarget(bottomNavigation.getViewAtPosition(2));

**Comment by sjwall** [comment]
Thanks @nightstorm99 for answering this
