### ISSUE TITLE
How to set target for Toolbar overflow menu

### ISSUE THREAD

**Issue by pavelpoley** [sjwall/MaterialTapTargetPrompt#195]
How to set target for Toolbar overflow menu? 
I looked into the layout inspector and the Toolbar overflow menu has no id...

**Comment by sjwall** [comment]
There is an example here:

 https://github.com/sjwall/MaterialTapTargetPrompt/blob/099d7519c33be4b6d0dad2179b61fc1c6b97d602/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/MainActivity.java#L174

or for a child item:

https://github.com/sjwall/MaterialTapTargetPrompt/issues/73#issuecomment-320681655
