### ISSUE TITLE
How to adjust the spacing of secondary text lines?

### ISSUE THREAD

**Issue by SAEEDHONARI** [sjwall/MaterialTapTargetPrompt#199]
How to adjust the spacing of secondary text lines?

**Comment by sjwall** [comment]
Using a custom [PromptText](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptText.java) [builder.setPromptText](https://sjwall.github.io/MaterialTapTargetPrompt/javadoc/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setPromptText(uk.co.samuelwall.materialtaptargetprompt.extras.PromptText)) the text can be complete customised
