### ISSUE TITLE
Add functionality for setting (on/off) animation near target view + text gravity

### ISSUE THREAD

**Issue by drstranges** [sjwall/MaterialTapTargetPrompt#20]
It could be nice if you add setter to enable/disable animation above target view (ripple and so on) and ability to set text gravity. Those are only things not allowing me to use your library without copy/paste with modification.

**Comment by sjwall** [comment]
Hey, the enable/disable animation is covered in your pull request in #21 and with the text positioning I will add the functionality choose where it positions the text above/below and left/right. This is what you are after with the gravity?

**Comment by drstranges** [comment]
Yes,  enable/disable animation is covered in my pull request, but text positioning is not. It would be nice if you add the setter (if  it is enaugh) for positioning primary text and secondary text with left/right/center gravity.

**Comment by sjwall** [comment]
I shall look into it

**Comment by sjwall** [comment]
I just need to test it some more and then I will release it tomorrow

**Comment by sjwall** [comment]
Thanks for your help, this has been released in v1.6.0
