### ISSUE TITLE
3.3.1 update causes text to render weirdly with alpha effected by view background

### ISSUE THREAD

**Issue by peterdk** [sjwall/MaterialTapTargetPrompt#201]
**Describe the bug**
I updated from 3.3.0 to 3.3.1, without changing anything else. I now have my white text in the popups being blended with the background making it unreadable. I wanted to go for 3.3.1 since the text popup outside the circle at start was bothering me. Great library!

**To Reproduce**
Steps to reproduce the behaviour including how the prompt builder is created:
```   
                 MaterialTapTargetPrompt.Builder(activity).setTarget(target)
                .setPrimaryText(primaryText)
                .setSecondaryText(secondaryText)
                .setFocalColour(activity.getResources().getColor(R.color.umito_orange_transparent))
                .setBackgroundColour(
                    activity.getResources().getColor(R.color.actionbar_grey_transparent)
                )
                .setPromptStateChangeListener { prompt, state ->
                    if (state == MaterialTapTargetPrompt.STATE_DISMISSED) {
                        showNextPrompt()
                    } else if (state == MaterialTapTargetPrompt.STATE_FOCAL_PRESSED) {
                        prompt.dismiss()
                    }
                }
                .setCaptureTouchEventOnFocal(true)
                .setCaptureTouchEventOutsidePrompt(true)
                .show()
```

**Expected behavior**
Text shows without being affected by views under background of the prompt

**Screenshots**
3.3.0:
![3 3 0](https://user-images.githubusercontent.com/668007/140622916-ead98ad6-c1b7-4ee6-9982-f349d8439acb.png)
3.3.1:
![3 3 1](https://user-images.githubusercontent.com/668007/140622919-a0b1ed9a-59e3-49bc-a67a-7d33ae689df9.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 12
 - Library version 3.3.1

**Additional context**
I think it has to do with the Xtransfer mode being set in #146

**Comment by peterdk** [comment]
I did some tinkering with the code, and instead of the Xtransfermode in the PromptText, I just clip the text with a new property of PromptBackground that supplies the background's path. Now hardware layer works as well, and no weird effects. I would say that is a better approach. 

```
 //Draw the text
            Path backgroundPath = mPromptOptions.getPromptBackground().getPath();
            if (backgroundPath != null) {
                canvas.save();

                canvas.clipPath(backgroundPath, Region.Op.INTERSECT );
            }
            mPromptOptions.getPromptText().draw(canvas);
            if (backgroundPath != null) {
                canvas.restore();
            }
```

I can make a more official PR for it, and testing with the other backgrounds as well and implementing the path for them.

**Comment by peterdk** [comment]
I created a PR, it fixes the issue. Let me know if it is acceptable or needs changing.

**Comment by danilodanicomendes** [comment]
Damn, seems like I only thought of my use case with that xfermode change. Sorry about that. 
To fix this, keeping PorterDuff, would definitely add a lot of complexity (if fixable at all)

I looked at your PR and I do agree that this is a better approach and more bullet proof for other use cases.

**Comment by peterdk** [comment]
No problem, it was nice seeing someone having the same intent to fix the issue! You can't account for all cases, and I assume it worked for your case.
