### ISSUE TITLE
Show on an android.app.Dialog

### ISSUE THREAD

**Issue by paolinho91** [sjwall/MaterialTapTargetPrompt#204]
Hi, thanks for your incredible work.
I tried to make a MaterialTapTargetPrompt on a Dialog, but the view appear behind the dialog and not on it.

```
            new MaterialTapTargetPrompt.Builder(activity)
                    .setTarget(_edit_text_)
                    .setPrimaryText(R.string....)
                    .setSecondaryText(R.string...)
                    .setPromptFocal(new RectanglePromptFocal())
                    .setCaptureTouchEventOnFocal(true)
                    .setCaptureTouchEventOutsidePrompt(true)
                    **.setClipToView(_main_dialog_card_view_)**
                    .show();
```
![photo_2022-02-13_23-34-10_B](https://user-images.githubusercontent.com/12999127/153778309-150241af-17bb-46da-8325-f8fc6c1f1046.jpg)

probably setClipToView is not working in my case?

Could you help, me, please?

**Comment by sjwall** [comment]
Hey, thanks for the kind words

You need to pass the dialog, not the activity to the constructor: https://sjwall.github.io/MaterialTapTargetPrompt/javadoc/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.Builder.html#%3Cinit%3E(android.app.Dialog)

**Comment by paolinho91** [comment]
Hi, thanks for your reply. Unfortunately now I obtain an exception:

  ```
  java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
        at uk.co.samuelwall.materialtaptargetprompt.ActivityResourceFinder.getResources(ActivityResourceFinder.java:72)
        at uk.co.samuelwall.materialtaptargetprompt.extras.PromptOptions.<init>(PromptOptions.java:208)
        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init>(MaterialTapTargetPrompt.java:1158)
        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init>(MaterialTapTargetPrompt.java:1116)
        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.<init>(MaterialTapTargetPrompt.java:1100)
```
could you help me?
Thanks

**Comment by paolinho91** [comment]
Hi, any ideas?

**Comment by sjwall** [comment]
Apologies for the late reply, the NPE is caused because the activity passed to the prompt builder is null

**Comment by paolinho91** [comment]
Hi, thanks for your reply. I'm passing to the prompt builder the displayed Dialog as you wrote me in the first comment...

**Comment by sjwall** [comment]
On the dialog that is passed into the builder what does the call to `dialog.getOwnerActivity()` return? Presuming it is null. Looks like `setOwnerActivity` needs to be called https://stackoverflow.com/a/13956305/8345775

**Comment by paolinho91** [comment]
Magical, it works. You saved me time, i really didn't understand why this behaviour....many thanks.

**Comment by sjwall** [comment]
Glad to hear it's working! Happy to help. I don't understand it either... but it works
