### ISSUE TITLE
Target focus shows below actionmode in 1.6 version

### ISSUE THREAD

**Issue by chinmoyeedash** [sjwall/MaterialTapTargetPrompt#22]
I was using 1.1.4 version which shows the target correctly over the actionmode, but now if i update the dependency to 1.6, the target shows below the actionmode.

**Comment by sjwall** [comment]
I shall investigate and see what I can do to fix it

**Comment by sjwall** [comment]
This should be fixed in release v1.6.1. Please let me know how you get on with it :)

**Comment by chinmoyeedash** [comment]
Nope.. 1.6.1 also didn't help

**Comment by sjwall** [comment]
Could you please provide more detail on the following so that I can try and replicate it better:

* How you are targeting the actionmode `setTarget(View)`?
* What actionmode you are using: [Android](https://developer.android.com/reference/android/view/ActionMode.html), [support library](https://developer.android.com/reference/android/support/v7/view/ActionMode.html) or custom?
* How are you creating the actionmode?
* What version of Android?

Thanks

**Comment by chinmoyeedash** [comment]
- Setting target by --- setTarget(findViewById(R.id.menu_next))

- using action mode - support library-v7

- creating actionmode on listview selections
   if (hasCheckedElement && mode == null)
         	// there are some selected items, start the actionMode
               mode = startSupportActionMode(new ModeCallback());

- Tested it on my Android 5.0 and 4.2.2

**Comment by sjwall** [comment]
I have changed the example to use `findViewById` but I am still unable to replicate.
You could try wrapping the prompt creation in a `post` like below. The support `ActionMode` uses this as well. If the `post` fixes the issue for you I will add it into the library (I need to do some more research but I think it should be doing this anyway).

```java
getWindow().getDecorView().post(new Runnable() {
    @Override
    public void run() {
        // Create prompt here
    }
});
```

You could also try running the sample app (cloning or from the play store) and seeing if that has the issue and if it has any differences to your implementation.

Let me know if this helps

**Comment by sjwall** [comment]
No response for a month so assuming that your question has been answered. Please reopen if not
