### ISSUE TITLE
Usage is not flexible enough for fragments / dialogfragments

### ISSUE THREAD

**Issue by hwesley** [sjwall/MaterialTapTargetPrompt#24]
I'm using your library in my app. I noticed it's strongly connected to an activity for usage. 

I have a DialogFragment in my app (bottom sheet) which is displayed in a different window / decorview than the one from my activity. When I trigger the prompt it is thus shown behind the dialog.

By changing the constructor & builder so it accepts a context (instead of activity) and a decorview,  usage is a lot more flexible. 

Any chance this could be changed in your library?

**Comment by sjwall** [comment]
I shall look into what options there are for decoupling it from activity

**Comment by RJFares** [comment]
+1

**Comment by venu1412** [comment]
+1
I am also facing the same issue , Can i know any tentative schedule when this bug will get fixed.

**Comment by sjwall** [comment]
I am currently working on this, hopefully it won't take more than a couple of weeks

**Comment by sjwall** [comment]
This change has been released in v1.11.0.

The [ResourceFinder](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/ResourceFinder.java) interface is used to find the required resources with an implementation for [dialogs](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/DialogResourceFinder.java) and [activities](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/ActivityResourceFinder.java) supplied with the library.
