### ISSUE TITLE
How to make target visible?

### ISSUE THREAD

**Issue by lance2611** [sjwall/MaterialTapTargetPrompt#27]
I've read somewhere here that the way to make the target visible is to .setFocalColour(Color.TRANSPARENT) but when I did that, the focal color turns black. Is there other way to do this? I don't want to set a drawable icon, I just want the target to be visible.

**Comment by sjwall** [comment]
Using just `setTarget(View)` will show the target above the prompt without the need for setting an icon.
Using `Color.TRANSPARENT` will draw black due to the way the colour is applied in Android.

**Comment by sjwall** [comment]
It should be noted that: if the target is white and the focal colour is white, it will not be possible to see the target.

**Comment by sjwall** [comment]
No response for a month so assuming that your question has been answered. Please reopen if not
