### ISSUE TITLE
more shapes other than circle.

### ISSUE THREAD

**Issue by Frankenstein666** [sjwall/MaterialTapTargetPrompt#28]
Can you make more regular shape for focal beside circle, like rectangle, rounded rectangle, that would be awesome.

**Comment by sjwall** [comment]
It would be awesome to have but currently I am just focusing on the Material Design Guidelines. Anyone is more than welcome to submit a pull request that abstracts the background shape so that other shapes can be used.

**Comment by danieltigse** [comment]
That would be awesome!!

**Comment by wisien92** [comment]
Agreed. That would be awesome.

**Comment by sajadmaster** [comment]
That would be awesome!!!

**Comment by sjwall** [comment]
This is a work in progress in the [shapes](https://github.com/sjwall/MaterialTapTargetPrompt/tree/shapes) branch and plan to release it in v2.2.0

![screenshot_1505848765](https://user-images.githubusercontent.com/16527946/30611000-01f74e3c-9d78-11e7-90c4-d59ee1c34ff1.png)

**Comment by sjwall** [comment]
This is now released in v2.2.0. Have a look at the [PromptBackground](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptBackground.java) and [PromptFocal](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptFocal.java) classes.
A rectangle implementation is provided through the [RectanglePromptBackground](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/backgrounds/RectanglePromptBackground.java) and [RectanglePromptFocal](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/focals/RectanglePromptFocal.java)
