### ISSUE TITLE
issue with forced RTL support

### ISSUE THREAD

**Issue by hisham2007** [sjwall/MaterialTapTargetPrompt#29]
Many thanks for great effort. I developed an Arabic news reader 
[https://play.google.com/store/apps/details?id=com.tabe3.news&hl=en](https://play.google.com/store/apps/details?id=com.tabe3.news&hl=en)

So I force RTL. when I use MaterialTapTargetPrompt to showcase toolbar item using:

` tapTargetPromptBuilder.setTarget(tb.getChildAt(1));`

there is a strange behavior happens. it highlights areas in left of toolbar.

I use this code to force RTL:

```Java
try {
    String languageToLoad = "ar"; // your language
    Locale locale = new Locale(languageToLoad);
    Locale.setDefault(locale);
    Configuration config = activity.getResources().getConfiguration();
    //config.locale = locale;
    config.setLocale(locale);
    activity.getResources().updateConfiguration(config, activity.getResources().getDisplayMetrics());
    activity.getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
} catch (Exception ex){
    Crashlytics.logException(ex);
    LogUtil.e(ex);
}
```

**Comment by sjwall** [comment]
I have tried forcing RTL using your code and it appears to work fine in the sample.

Does it target correctly when not forcing RTL?

Is it targeting the right view? `getChildAt` is not a brilliant way to target a view but I have not been able to find another way to target an app bar action button.

![screenshot_1482149142](https://cloud.githubusercontent.com/assets/16527946/21312714/aa2505ec-c5e5-11e6-8f74-db7e73ecec80.png)

**Comment by hisham2007** [comment]
you didnt try what i mean. I didnt mean navigation item

try to add a menu item . "search menu item" for example

**Comment by sjwall** [comment]
I think I can replicate the issue described, in the screenshot below the prompt is showing between two app bar buttons

![screenshot_1482345949](https://cloud.githubusercontent.com/assets/16527946/21401846/c22790e6-c7ad-11e6-861f-caeb00cab19e.png) ![screenshot_1482345654](https://cloud.githubusercontent.com/assets/16527946/21401821/a2a1e550-c7ad-11e6-8c38-bbe029727dad.png)

**Comment by sjwall** [comment]
The sample example was targeting the wrong view.
To target an app bar action icon simply supply the item id, for example:

Menu xml:
```xml
<item
        android:id="@+id/action_search"
        android:icon="@drawable/ic_search"
        android:title="Search" />
```
Prompt creation:
```Java
new MaterialTapTargetPrompt.Builder(this).setTarget(R.id.action_search)
```

To target the overflow icon I haven't been able to find a better way than getting the last child in the action item container:

```Java
        final Toolbar tb = (Toolbar) this.findViewById(R.id.toolbar);
        final View child = tb.getChildAt(2);
        if (child instanceof ActionMenuView)
        {
            final ActionMenuView actionMenuView = ((ActionMenuView) child);
            tapTargetPromptBuilder.setTarget(actionMenuView.getChildAt(actionMenuView.getChildCount() - 1));
        }
```

The sample app has been updated with this in 7ca2778.
Does this solve the issue you are having?

**Comment by hisham2007** [comment]
I will try it. many thanks for your effort

**Comment by sjwall** [comment]
No response for a month so assuming it is fixed. Please reopen if not
