### ISSUE TITLE
Follow the Material Design Guidelines on positioning the prompt in the centre of the screen

### ISSUE THREAD

**Issue by sjwall** [sjwall/MaterialTapTargetPrompt#3]
Currently the prompt positioning is not correct if the target is in the centre of the screen

**Comment by adroitandroid** [comment]
@sjwall thanks for the library! Can you please point to any clear guideline spec for this, if there is one?

**Comment by sjwall** [comment]
In the [Feature discovery - Design](https://material.io/guidelines/growth-communications/feature-discovery.html#feature-discovery-design) section it states the following:

> When the prompted action is located toward the center of the screen, the prompt background should be adjusted as follows:
> 
> - Tap targets located right of the screen’s center: The prompt background should be offset 20dp to the left
> - Tap targets located left of the screen’s center: The prompt background should be offset 20dp to the right
> - If the tap target is in the center of screen: The prompt background will be offset automatically to the right or left depending on language

The same section contains further information on how to position tap targets on mobile, tablet and desktop.

**Comment by sjwall** [comment]
Implemented and released in v1.8.0
