### ISSUE TITLE
ClipToView assumes first child is a view group

### ISSUE THREAD

**Issue by guidedways** [sjwall/MaterialTapTargetPrompt#30]
I'm not using a ViewGroup as the first child of R.id.content (I've got a `<merge>` tag at the top for performance reasons and then the first child itself is a normal View). The app crashes at this line:

`mPrompt.mClipToView = (ViewGroup) ((ViewGroup) mActivity.findViewById(android.R.id.content)).getChildAt(0);`

**Comment by sjwall** [comment]
Missed that use case when designing the library. Change the default view that is clipped to, to the content view.

**Comment by sjwall** [comment]
The fix has been released in v1.7.0. Please let me know how you get on

**Comment by sjwall** [comment]
No response for a month so assuming it is fixed. Please reopen if not
