### ISSUE TITLE
Doesn't support transparent or semi-transparent color

### ISSUE THREAD

**Issue by KashifAnwaar** [sjwall/MaterialTapTargetPrompt#33]
Hi there!
Amazing job making this library, but it doesn't support transparent or semi-transparent colors, 
**if we set focal color with transparency it removes transparency, 
if we set non-transparent background color it sets transparency**

 please set the color exactly as we define in .setFocalColour(  ) and .setBackgroundColour(  ).

Thank you very much.

**Comment by sjwall** [comment]
Added two new methods to change the alpha values for the focal and background colours.

`setFocalColourAlpha(int)`
`setBackgroundColourAlpha(int)`

The alpha values follow the Material Design guidelines by default.

**Comment by SouhaibBenFarhat** [comment]
setFocalColourAlpha(int)
setBackgroundColourAlpha(int)

i cannot find those to two method to setup transparency

**Comment by sjwall** [comment]
The API changed in v2 with the alpha value now taken from the colour values supplied in `setFocalColour` and `setBackgroundColour`.
For example:

```java
builder.setFocalColour(Color.argb(alpha, red, green, blue));
```
