### ISSUE TITLE
Nonfunctional with disabled animations

### ISSUE THREAD

**Issue by HaukeRa** [sjwall/MaterialTapTargetPrompt#35]
The library is nonfunctional when disabling animations in the developer settings (as needed for automated tests)

In that case Android applies the animations twice, with the start and the end value. But it does that before mGlobalLayoutListener is called to update mBaseBackgroundRadius, which results in an always zero mBackgroundRadius.

This results in two problems:
1) The Background is not drawn
2) The motionEvent is never considered hitting the target or the background, the motion event is not captured and the overlay is never dismissed. This is the part which makes UI Tests impossible.

**Comment by sjwall** [comment]
hmmm so it does. Thanks for letting me know

**Comment by sjwall** [comment]
Fixed and released in v1.8.1. Please let me know if this release solves the issue for you

**Comment by HaukeRa** [comment]
Works fine, thanks!
