### ISSUE TITLE
Prompt positioned wrong

### ISSUE THREAD

**Issue by mindshifter** [sjwall/MaterialTapTargetPrompt#38]
Prompt positioned wrong in conjunction with this library 
[(https://github.com/Clans/FloatingActionButton)](url)

**Comment by sjwall** [comment]
Is this related to #15?

The fix for that issue is explained [here](https://github.com/sjwall/MaterialTapTargetPrompt/issues/15#issuecomment-255391451)

**Comment by mindshifter** [comment]
yes, thx a lot
