### ISSUE TITLE
Wrong target view Location When View Changed Upon Design Orientation Changes 

### ISSUE THREAD

**Issue by mzyadatuba** [sjwall/MaterialTapTargetPrompt#4]
When flipping the UI upon changing the application language from English to Arabic for example, the target view will move from the left to the right, but the material tap target prompt still sees the target view on the left and it starts from the left of the screen.

**Comment by sjwall** [comment]
Issue was the prompt view never changing position if the target view moved

**Comment by mzyadatuba** [comment]
Will check it now .. thanx

**Comment by mzyadatuba** [comment]
Working 100%
