### ISSUE TITLE
Do not use an icon for target

### ISSUE THREAD

**Issue by checklist** [sjwall/MaterialTapTargetPrompt#44]
Great job! Really like your implementation!

I would like to target some text area on the screen but do not use an icon there. Is there a way to target an area without using an icon? If I do not specify an icon I simply get a white space there. It should be transparent. I tried the following but did not seem to work:

`tapTargetPromptBuilder.setIconDrawableColourFilter(activity.getResources().getColor(R.color.transparent));
`
and colors.xml:

`<color name="transparent">#00000000</color>`

I am trying out the library. Maybe I am missing something?

Thanx!

**Comment by sjwall** [comment]
You can use any view as a target using `setTarget`. The library does not currently support fully transparent colours
