### ISSUE TITLE
Target as a View inside a ListView row example

### ISSUE THREAD

**Issue by checklist** [sjwall/MaterialTapTargetPrompt#45]
Hi,

I am trying to set the target of the MaterialTapTargetPrompt as a view of a row of a list view in an activity. Unfortunately, the focus is at the top left of the screen instead on on the view given as target.

Can this library be used with list views?

Thanks so much!

**Comment by checklist** [comment]
I figured out that calling the show() method from the onCreate was the issue. Put it in a Handler with a 1000 delay and all became good!

I would suggest adding this to some doc to avoid wasting time for others.

Thanks.

**Comment by sjwall** [comment]
The item views in a list view won't have been created during `onCreate` hence the need for a delay. It would be better to target the list view items after creation by using a listener on the list view. I will add list view example (there is already a RecyclerView on) with the prompt shown when the items are added.

**Comment by sjwall** [comment]
List example added in commit 1dc578807bfd4c3bad468a90561586e77510a164
