### ISSUE TITLE
NPE 

### ISSUE THREAD

**Issue by checklist** [sjwall/MaterialTapTargetPrompt#46]
Hi,

I am having a NPE exception in user's devices reported by Crashlytics. I am not sure what the cause is but this is the line where it happens: https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.java#L1037

`mPrimaryTextLayout.draw(canvas);`

And here is the exception:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.text.Layout.draw(android.graphics.Canvas)' on a null object reference
>        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$PromptView.onDraw(MaterialTapTargetPrompt.java:1037)
>        at android.view.View.draw(View.java:16435)
>        at android.view.View.updateDisplayListIfDirty(View.java:15388)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
>        at android.view.View.updateDisplayListIfDirty(View.java:15339)
>        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
>        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
>        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
>        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3020)
>        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2824)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2436)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
>        at android.view.Choreographer.doFrame(Choreographer.java:631)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
>        at android.os.Handler.handleCallback(Handler.java:815)
>        at android.os.Handler.dispatchMessage(Handler.java:104)
>        at android.os.Looper.loop(Looper.java:207)
>        at android.app.ActivityThread.main(ActivityThread.java:5728)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Any ideas? It is quite distressing as we are using the library to help people with onboarding and we are ending up with users getting crashes.

Thanks a lot for your help!

**Comment by sjwall** [comment]
Hey, the only scenario I can think that this might happen in is if the prompt view onDraw method is called before the prompt has finished setting up. With this in mind I have added a null pointer check to make sure that this scenario doesn't cause a crash.

This has been release in v1.9.2, if it doesn't solve the issue please reopen.

**Comment by checklist** [comment]
Hi Sam,

Thanks for the fix. Although a NULL check is good to have, it still does not solve the issue since it will mean the users will not see the primary or secondary text. That will be horrible user experience which is exactly what we are trying to improve with the use of your library. I can say that we got 0.3% of our reported Crashlytics users experience this so far. Had to hald the roll out due to it so I am quite concerned.

Unfortunately, we could not figure out what is wrong. Whether it is our use of the library or the library itself. Your help would be appreciated!

**Comment by sjwall** [comment]
Hey, I completely agree that would be bad user experience if the text was not shown. This is my bad for not saying but I also included a check for the background radius being greater than 0 before drawing anything. This means that nothing will be drawn if the text has not been created as the text needs to be created for the background radius to be calculated. So in the scenario I described before the prompt won't be drawn till the text is created which should be straight after the draw that was causing the crash.

If you could provide the Android version and device type that this is affecting I maybe able to find the root cause of this issue. I can't promise anything, but the above changes should have a good user experience anyway.

**Comment by checklist** [comment]
According to Crashlytics only Android 6.0.1, 4.4.4, 6.0, 5.1.1, 7.0, 5.1. Most of them were 6.0.1.
Let me know if there is anything else I can help with.
Thanx a lot Sam!
