### ISSUE TITLE
Prompt not displayed if only secondary text is set

### ISSUE THREAD

**Issue by agramian** [sjwall/MaterialTapTargetPrompt#47]
It seems like setting primary text is required to display the prompt.  If you only set the secondary text it does not show.

**Comment by sjwall** [comment]
I'll make it a requirement that either the primary or secondary text is required

**Comment by sjwall** [comment]
You could also style the primary text the same as the secondary text to get around this until v2.0.0 is released

**Comment by sjwall** [comment]
This change has been released in v1.11.0.
