### ISSUE TITLE
Update target sdk to 25

### ISSUE THREAD

**Issue by riinav** [sjwall/MaterialTapTargetPrompt#48]
Any plans to support API level 25

**Comment by sjwall** [comment]
It supports API level 25, it is just not built against it yet. I plan to update to build against API 25, haven't had the time to do it yet.

**Comment by sjwall** [comment]
Target SDK has been updated in 95be19cd9f3abdbf21344a06d7ece0389dbeb6a8 and will be released in v2.0.0
