### ISSUE TITLE
More flexibility with positioning and sizing circles and text

### ISSUE THREAD

**Issue by agramian** [sjwall/MaterialTapTargetPrompt#49]
It would be nice to have more control over sizing and positioning of the elements.

For example the ability to:

- [ ]  offset the center position of the larger outer circle so it is not perfectly centered around the target
- [ ] set a specific size for the larger outer circle rather than relying on the `textPadding` value
- [ ] ability to position the text relative to the target in the x and y directions individually rather than both together as it is now via the `focalToTextPadding`
- [ ] ability to offset/separate the primary and secondary text in both the x and y directions

**Comment by sjwall** [comment]
I am currently looking at possible options to make the library more customisable in v2.0.0. I will look into implementing your suggestions.

**Comment by Rainer-Lang** [comment]
+1

**Comment by matecode** [comment]
I think the "automagic" of the positions is really good.

At the moment the text is always above or below the target. It would be nice to have an option to say if the text above/below or left/right of the target.

**Comment by sjwall** [comment]
There isn't any methods added yet to do any of these but custom implementations can easily be implemented by extending the [PromptBackground](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptBackground.java) and [PromptFocal](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptFocal.java) classes or extending the provided circle and rectangle implementations.

**Comment by sjwall** [comment]
As mentioned in the above comment the functionality can be extended so specific unique use cases won't be implemented
