### ISSUE TITLE
focalColour does not take transparency into account

### ISSUE THREAD

**Issue by agramian** [sjwall/MaterialTapTargetPrompt#50]
The `focalColour` which is responsible for the circle drawn around the target does not seem to take into account transparency values for the color used.  The pulsating/animating color associated with the `focalColour` does seem to have transparency but not the `focalColour` itself.

**Comment by sjwall** [comment]
Need to use the method `setFocalColourAlpha`. Originally the focal transparency was not modifiable so to keep the library functionality consistent `setFocalColourAlpha` was added to do this. The `setFocalColourAlpha` method will be merged in to `setFocalColour` in v2.0.0

**Comment by sjwall** [comment]
Methods have been merged, this will be released in v2.0.0
