### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by MahdiTaghipour** [sjwall/MaterialTapTargetPrompt#52]
Hi, 
I have detect a crash on asus ME173X tablet with android version 4.2.2. I'll send you the crash log.
[crash_log.txt](https://github.com/sjwall/MaterialTapTargetPrompt/files/806624/crash_log.txt)

**Comment by sjwall** [comment]
It looks like you are targeting an `ImageView` which has a drawable that is a `pl.droidsonroids.gif.GifDrawable` but the image that is being draw by `GifDrawable` has been recycled.

At which point is the error occurring, when the prompt is shown or tapped?
Are you manipulating the `ImageView` when the prompt is shown?

**Comment by MahdiTaghipour** [comment]
yes we have an image view and we have set the image view a gif.
we have crash reporter and this crash was recorded in our crash log. so I don't know at which point this error has been occured.
