### ISSUE TITLE
Button overlapping circle

### ISSUE THREAD

**Issue by krisdev-pl** [sjwall/MaterialTapTargetPrompt#53]
![screenshot_2017-03-04-21-10-14](https://cloud.githubusercontent.com/assets/25513676/23581936/32de7e44-011f-11e7-9ab5-3597b8fcadab.png)

How can I display circle above button?

**Comment by sjwall** [comment]
The library is intended to follow the Material Design Guidelines on Tap Target. These guidelines currently don't specify how to target views that have a different width to height. 

You can increase the radius of the white area (focal) using `setFocalRadius`

**Comment by FidaMOhsin** [comment]
Add this line to Builder and see the magic :) ->  .setPromptFocal(RectanglePromptFocal())
