### ISSUE TITLE
Transparent focal color?

### ISSUE THREAD

**Issue by creativetrendsapps** [sjwall/MaterialTapTargetPrompt#54]
Is there a way to set the focal color to transparent? When setting it transparent there is a dark tint instead of the color being transparent.

**Comment by sjwall** [comment]
This can be done using `setFocalColourAlpha`. This method will be merged into `setFocalColour`  and `Color.TRANSPARENT` properly supported in v2.

**Comment by lidkxx** [comment]
When my target is a TabLayout ViewPager's textview, neither `setFocalColour` nor `setFocalColourAlpha` seem to work. When I use `setFocalColour`there is black tint instead, and when I use `setFocalColourAlpha` the focal circle just gets the same tint as the background (outer) circle.
