### ISSUE TITLE
Allow to set not target

### ISSUE THREAD

**Issue by marbat87** [sjwall/MaterialTapTargetPrompt#56]
It would be nice to allow to set no target.
So only the colored circle and the texts would appear.
For example it could be used for a summary of the activity functionality, without ant specific target description

Thanks in advance,
Marcello

**Comment by sjwall** [comment]
The example below should give you what you are after:
```java
builder.setTarget(0,0)
       .setIdleAnimationEnabled(false)
       .setFocalColourAlpha(0)
```
![screenshot_1489332177](https://cloud.githubusercontent.com/assets/16527946/23833061/4f3c33be-0738-11e7-9dd3-0d458198bbf8.png)
