### ISSUE TITLE
[UI issue] View overlay in landscape

### ISSUE THREAD

**Issue by tzutalin** [sjwall/MaterialTapTargetPrompt#58]
![screenshot_20170322-230727](https://cloud.githubusercontent.com/assets/3283822/24238182/5a6a8538-0fe4-11e7-8622-8c71b2ac92b6.jpg)

**Comment by sjwall** [comment]
I haven't been able to replicate this. Could you please provide more information on what you are targeting in the view, how you are targeting it and what android version? Thanks
