### ISSUE TITLE
Position background circle differently

### ISSUE THREAD

**Issue by lidkxx** [sjwall/MaterialTapTargetPrompt#59]
Hey!
First of all thank you for the amazing work with this library. It helped me a ton!

I have a question regarding positioning of the background circles. Is there a way to position them differently than the library defaults to?

Here's what I am trying to achieve:
![zrzut ekranu 2017-03-23 o 15 57 04](https://cloud.githubusercontent.com/assets/1851490/24253843/ab186232-0fe1-11e7-8641-77e8e3e1eae2.png)

The circle should be centered horizontally and the texts should be under the focal circle.
Appreciate your help!

**Comment by sjwall** [comment]
I am working on adding functionality to override the auto positioning, this is being covered under #49
