### ISSUE TITLE
App Crashes on start

### ISSUE THREAD

**Issue by GalaxyS5S6S7S8** [sjwall/MaterialTapTargetPrompt#60]
I want to use your Library (which is very pretty) in a fragmentview of a Navogation Drawer. but my app crashes directly on start...

**Comment by sjwall** [comment]
Could you provide more information such as a stacktrace, the android version and how the prompt is being created so that I can investigate, thanks

**Comment by sjwall** [comment]
Please reopen and provide more detailed information if this is still an issue, thanks
