### ISSUE TITLE
Focus circle overlaps elements drawn on canvas

### ISSUE THREAD

**Issue by Sauvikk** [sjwall/MaterialTapTargetPrompt#61]
I don't know if this is expected behavior or not but I was trying to focus on an element inside a canvas and noticed that the inner circle overlaps the element in focus. This does not happen when I set the target as a view.

[int[] loc = new int[2];
        mChart.getLocationInWindow(loc);
        Circle circle = chartPointCache.getCircle(1);
        int x = (int) (circle.getCenterX() + loc[0]);
        int y = (int) (circle.getCenterY() + loc[1]);
        new MaterialTapTargetPrompt.Builder(getActivity())
                .setTarget(x, y)
                .setPrimaryText("")
                .setSecondaryText(getString(R.string.budget_txt))
                .show();](url)

Here I am using the (x,y) to set the target. 
Please let me know if it's possible to overcome this issue ?

**Comment by sjwall** [comment]
I have made changes to the positioning calculations in v1.9.4 which should fix this. Could you try this release?
If it doesn't solve it, reopen this issue and could you please let me know the coordinates on screen and screen size so I can debug further? 
Thanks
