### ISSUE TITLE
[Question] Why should codes be divided into smaller parts?

### ISSUE THREAD

**Issue by quangctkm9207** [sjwall/MaterialTapTargetPrompt#67]
Thank you for a really nice library.  

I have looked at your source code, and I am really impressive that it is elegant and well documented.
However, at the moment all of your work is in only one class. 
I just have a small question that why you do not break them down into smaller parts? Personally, I think it is better to follow and maintain.

**Comment by sjwall** [comment]
The library was originally designed to be similar to an `AlertDialog` with the `Builder` class as an inner class to be used in one of my own projects. With direct access to the source to change as needed there wasn't a need to move the inner classes out and before moving it to a standalone library there was < 1000 lines. The `MaterialTapTargetPrompt` class has now doubled in size from ~1300 lines in the first library commit to ~2600 lines, making it a lot less maintainable. I am looking at moving classes out to make it more extendable and maintainable.

Let me know if you have any more questions

**Comment by searchy2** [comment]
I think libraries should have as few classes as possible. For example, a library that has a RecyclerView should place the adapter and viewholder classes in the same file as the business logic. You wouldn't do this in an app but for a library it is much more elegant than having multiple folders and files.
