### ISSUE TITLE
Wrong behavior with ActionBar

### ISSUE THREAD

**Issue by nicolabeghin** [sjwall/MaterialTapTargetPrompt#68]
Hi 
Is this library compatible with Toolbar only? When targeting a MenuItem in an Action Bar (AppCompatActivity) the overlay is below the action bar. 

Thanks 
Nicola

**Comment by zacharee** [comment]
I'm having this issue too. Setting the ClipToBounds option works to show it above the ActionBar view, but then, of course, it doesn't have room to show text or anything.

**Comment by sjwall** [comment]
I have been unable to replicate this. What android version and support library version are you using? Also how are you creating the prompt and finding the view that is the target?

With this information I should be able to investigate further.

**Comment by nicolabeghin** [comment]
hi @sjwall 
below the content of `build.gradle`

```
dependencies {
    compile project(':aFileChooser')
    compile 'com.android.support:appcompat-v7:25.4.0'
    compile 'com.android.support:support-v4:25.4.0'
    compile 'com.android.support:design:25.4.0'
    compile 'de.mindpipe.android:android-logging-log4j:1.0.3'
    compile 'uk.co.samuelwall:material-tap-target-prompt:1.10.0'
    compile 'com.github.apl-devs:appintro:v4.2.0'
    compile 'log4j:log4j:1.2.17'
}
```

I'm using `android.support.v7.app.AppCompatActivity` and binding the library on a `MenuItem`:

```java
if (settings.getBoolean("highlightedContactMe", false) == false) {
    new MaterialTapTargetPrompt.Builder(MainActivity.this)
        .setTarget(R.id.itemContact)
        .setPrimaryText("I'm here to help!")
        .setSecondaryText("Just drop me a line")
        .setBackgroundColourFromRes(R.color.colorPrimary)
        .setOnHidePromptListener(new MaterialTapTargetPrompt.OnHidePromptListener() {
            @Override
            public void onHidePrompt(MotionEvent event, boolean tappedTarget) {

            }

            @Override
            public void onHidePromptComplete() {
                SharedPreferences.Editor editor = PreferenceManager.getDefaultSharedPreferences(getApplicationContext()).edit();
                editor.putBoolean("highlightedContactMe", true);
                editor.apply();
            }
        })
        .show();
}
```
thanks
nicola

**Comment by sjwall** [comment]
I have managed to replicate the issue and am working on a fix for it
![screenshot_1501095270](https://user-images.githubusercontent.com/16527946/28638343-7fa66762-723c-11e7-81b7-6bf2fd5b709f.png)

**Comment by sjwall** [comment]
I am still working on a fix for this but have found a workaround in the mean time.
Set the decor view as the view that the prompt is clipped to:
```Java
builder.setClipToView(getWindow().getDecorView());
```

**Comment by sjwall** [comment]
I have fix, just need to test it further and fix some other issues with targeting the navigation and overflow items in the app bar when it is in the decor view.

**Comment by sjwall** [comment]
This has been fixed and released in v1.12.1

**Comment by Raghu479** [comment]
Hi I am getting the issue , that even the action bar is not there, it leaving the space above and occupying total space on the top.
![screenshot_2019-01-09-18-04-06-349_com reallymake android pottery 1](https://user-images.githubusercontent.com/46526604/50899817-441db600-1439-11e9-9494-8d9c4e85c6e5.png)

**Comment by Alok191196** [comment]
Try this it worked for me
`setClipToView(null)`
