### ISSUE TITLE
Feature Request: public access to PromptView field and class

### ISSUE THREAD

**Issue by agramian** [sjwall/MaterialTapTargetPrompt#70]
I have a use case that requires the ability to determine the size and position information regarding the `PromptView` and the text views within it in order to adjust custom ui elements relative to them.

Currently the `PromptView` class is an inner class with no public access.  I'm proposing to make the `PromptView` class public and the `mView` field of the `MaterialTapTargetPrompt` class accessible through a public getter method.

I would also like to request the addition of some public methods to the `PromptView` class to be able to get references to the text layouts and/or their size and position info.

Because the info is not available until the `PromptView` is drawn,  an additional `MaterialTapTargetPrompt.Builder` method to `setOnShowPromptListener()` would need to be added as well.

**Comment by sjwall** [comment]
I am looking at making `PromptView` extendable through the new `ResourceFinder` interface.
There is a new [setPromptStateChangeListener](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.Builder.html#setPromptStateChangeListener-uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.PromptStateChangeListener-) released in v1.11.0 which provides more events when the prompt is shown and dismissed.

**Comment by sjwall** [comment]
Covered by #193
