### ISSUE TITLE
Issue when building using Support Library 26

### ISSUE THREAD

**Issue by Pika3323** [sjwall/MaterialTapTargetPrompt#71]
When trying to build an app using the support library version 26.0.0-beta2, the following errors occur:
`
C:\Users\derek\StudioProjects\Transpo\app\build\intermediates\res\merged\alpha\debug\values\values.xml
Error:(631) Attribute "iconTint" already defined with incompatible format.
Error:(34) Original attribute defined here.
Error:(631) Attribute "iconTintMode" already defined with incompatible format.
Error:(35) Original attribute defined here.
Error:(631) Attribute "iconTint" already defined with incompatible format.
Error:(34) Original attribute defined here.
Error:(631) Attribute "iconTintMode" already defined with incompatible format.
Error:(35) Original attribute defined here.
`

When the library is removed, the project builds normally so it is definitely isolated to this library.

**Comment by yoavst** [comment]
Yea, renaming attributes is required. We should add prefix to all the attributes.

**Comment by Agrahyah** [comment]
any workarounds until new version with prefix is released

**Comment by yoavst** [comment]
@Agrahyah Copy the sources to your project and edit.

**Comment by sjwall** [comment]
There is a fork with the attributes renamed [here](https://github.com/Tractive/MaterialTapTargetPrompt/commit/b8a2e688a8f60f59fc33aa51926e4200e845ab2d). I am looking at putting the renamed attributes into the next release.

**Comment by TinasheMzondiwa** [comment]
When will v2.0.0 be released?

**Comment by alexeyvasilyev** [comment]
Support library version 26.0.0 has just been released. When do you plan to release MaterialTapTargetPrompt 2.0.0?

**Comment by sjwall** [comment]
Hopefully I will have it completed by 6th August.

**Comment by fghamsary** [comment]
Waiting impatiently for this fix 👍

**Comment by sjwall** [comment]
Almost there with it, some last minute teething issues that I hope to resolve tomorrow. Apologies for the delay.

**Comment by sjwall** [comment]
Version 2.0.0 has been released and includes the fix for this issue.
