### ISSUE TITLE
How to add tap target on option menu in toolbar?

### ISSUE THREAD

**Issue by ghozien** [sjwall/MaterialTapTargetPrompt#73]
How to add tap target on option menu in toolbar?
this option menu create on method onCreateOptionsMenu, and I want to show tap target on that option menu onCreate Activity.

**Comment by sjwall** [comment]
To target an item shown in a [Toolbar](https://developer.android.com/reference/android/support/v7/widget/Toolbar.html) set the target as the item id. Examples of this can be seen in the [MainActivity](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/MainActivity.java) example in the methods `showOverflowPrompt` and `showSearchPrompt`

```Java
builder.setTarget(R.id.item_id);
```

I have yet to figure out a way to target an item in the overflow drop down menu.

**Comment by ghozien** [comment]
I want to show tap target in menu item on activity start.

**Comment by sjwall** [comment]
I shall investigate this further to see how to target a menu item in a menu

**Comment by SUPERCILEX** [comment]
I've got this working just fine:
```kt
override fun onCreateOptionsMenu(menu: Menu): Boolean {
    menuInflater.inflate(R.menu.team_list_menu, menu)
    authHelper.initMenu(menu)
    Handler().post { showSignInPrompt(this) }
    return true
}
```

And:
```kt
fun showSignInPrompt(activity: Activity) {
    val appContext = activity.applicationContext
    if (hasShownAddTeamTutorial(appContext) && !hasShownSignInTutorial(appContext)) {
        MaterialTapTargetPrompt.Builder(activity, R.style.RobotScouter_Tutorial_Menu)
                .setTarget(R.id.action_sign_in)
                .setPrimaryText(R.string.sign_in)
                .setSecondaryText(R.string.sign_in_rationale)
                .setOnHidePromptListener(object : MaterialTapTargetPrompt.OnHidePromptListener by EmptyOnHidePromptListener {
                    override fun onHidePrompt(event: MotionEvent, tappedTarget: Boolean) {
                        setHasShownSignInTutorial(appContext, tappedTarget)
                    }
                })
                .show()
    }
}
```

**Comment by ghozien** [comment]
What is the language you  used?

**Comment by SUPERCILEX** [comment]
@ghozien Kotlin. I can translate it into Java if it helps.

**Comment by ghozien** [comment]
Yes

**Comment by SUPERCILEX** [comment]
```java
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    getMenuInflater().inflate(R.menu.team_list_menu, menu);
    mAuthHelper.initMenu(menu);
    new Handler().post(new Runnable() {
        @Override
        public void run() {
            showSignInPrompt(this);
        }
    });
    return true;
}
```

Do you need the rest translated?

**Comment by ghozien** [comment]
Thanks for your answer.
And what is the function of mAuthHelper.initMenu(menu); ?

**Comment by SUPERCILEX** [comment]
Oh, that shouldn't matter.

**Comment by ghozien** [comment]
Thanks. It works.

**Comment by SUPERCILEX** [comment]
@sjwall I believe this issue can be closed.

**Comment by sjwall** [comment]
@SUPERCILEX Thank you for your help
