### ISSUE TITLE
Programatically dismiss prompt?

### ISSUE THREAD

**Issue by haldertaer** [sjwall/MaterialTapTargetPrompt#75]
Is there a way to programatically dismiss a prompt? Something like this: myPrompt.dismiss();

**Comment by sjwall** [comment]
When calling [show()](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.Builder.html#show--) or [create()](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.Builder.html#create--) from the [Builder](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.Builder.html) it returns a [MaterialTapTargetPrompt](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.html) instance that has a [Dismiss](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.html#dismiss--) method that can be called to dismiss the created prompt.

```Java
// ... create the builder
MaterialTapTargetPrompt prompt = builder.show()
prompt.dismiss();
```
