### ISSUE TITLE
Prompts get incorrect positioned when removing View

### ISSUE THREAD

**Issue by KSeyffarth** [sjwall/MaterialTapTargetPrompt#76]
### Issue
When removing a View from Window, while the prompt gets animated expanded, the center points position gets set to x=0, y=0 for a TargetView. 

See attached screenshot:

![2017-07-27_190911](https://user-images.githubusercontent.com/24591955/28682956-1e339f18-72ff-11e7-87a0-b3356df8e54f.png)

A solution for this could be an extra check for the View state before updating the center point position with `updateFocalCentrePosition()`.

### The following fix works fine for API 19:

        mGlobalLayoutListener = new ViewTreeObserver.OnGlobalLayoutListener()
            {
                @Override
                public void onGlobalLayout()
                {
                    final boolean isTargetAttachedToWindow = mTargetView.isAttachedToWindow();
                    if(mTargetView != null && !isTargetAttachedToWindow)
                    {
                        return;
                    }
                    updateFocalCentrePosition();
                }
            };

### And with support library (`ViewCompat`):

        mGlobalLayoutListener = new ViewTreeObserver.OnGlobalLayoutListener()
            {
                @Override
                public void onGlobalLayout()
                {
                    final boolean isTargetAttachedToWindow = ViewCompat.isAttachedToWindow(mTargetView);
                    if(mTargetView != null && !isTargetAttachedToWindow)
                    {
                        return;
                    }
                    updateFocalCentrePosition();
                }
            };

Issue appears in version 1.11.0 and Nexus 5 (API 23)

I would be happy to make a pull request for this solution.

**Comment by sjwall** [comment]
Thanks for the detailed solution, please do make a pull request for this. 

I am trying to not make the library dependant on the support libraries, so for API < 19 use `view.getWindowToken() != null` which is what the support library does.

Only one bug in your code is the mTargetView null check is after the `mTargetView.isAttachedToWindow()` call.

**Comment by KSeyffarth** [comment]
Thank you i made the Made the PR #77 for this fix.

**Comment by sjwall** [comment]
Fix merged and released in v1.12.0. Thank you for your contribution!
