### ISSUE TITLE
How to add prompt view to the Tabs in TabLayout 

### ISSUE THREAD

**Issue by NileshJarad** [sjwall/MaterialTapTargetPrompt#78]
I am stuck, I want to add tap prompt to tap every Tab in TabLayout

**Comment by sjwall** [comment]
If the Tab has a custom view you can do `tabLayout.getTab(index).getCustomView()`. If not the only other way that I have found so far is to manually find the view in the hierarchy which isn't a great way `((ViewGroup) tabLayout.getChildAt(0)).getChildAt(index)`

**Comment by NileshJarad** [comment]
tabLayout.getTab(index).getCustomView() solved my problem. Thanks @sjwall
