### ISSUE TITLE
Showcase under view

### ISSUE THREAD

**Issue by alizarei95** [sjwall/MaterialTapTargetPrompt#83]
Showcase drawn under target view. how to solve it?

**Comment by sjwall** [comment]
The prompt view is added to the [Android window Decor view](https://developer.android.com/reference/android/view/Window.html#getDecorView()) so the view you are targeting must be above the decor view or a child in the decor view. Without more information I am unable to help as I do not know what kind of view you are targeting or how. Please could you provide more information as per the [issue template](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by sjwall** [comment]
No feedback for more than a month so closing this issue. Please reopen this issue if this is still an issue.
