### ISSUE TITLE
Dim background

### ISSUE THREAD

**Issue by zhenyuan0502** [sjwall/MaterialTapTargetPrompt#84]
Hi @sjwall 
Should we have a dim background look like this? 
![image](https://user-images.githubusercontent.com/16673159/30859351-8024b400-a2ed-11e7-8609-dbab3242d54e.png)

Or a full screen dim background also is a good view 
![image](https://user-images.githubusercontent.com/16673159/30859498-388d234c-a2ee-11e7-94ab-f2b65300a740.png)

Thank you

**Comment by sjwall** [comment]
There doesn't appear to be anything in the material design guidelines detailing the examples you have given for a tap target, but once v2.2.0 is released they should be easy to implement by extending the newly added PromptBackground class.

**Comment by sjwall** [comment]
These can now easily be implemented by extending the [PromptBackground](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptBackground.java) and [PromptFocal](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptFocal.java) classes.
For the dimming the circle or rectangle background implementations could be extended and then override the draw method to draw a shaded rectangle before calling the super draw method.

Please let me know if you need more detail.
