### ISSUE TITLE
set target unclickable

### ISSUE THREAD

**Issue by sajastu** [sjwall/MaterialTapTargetPrompt#86]
Hi,
Can we set target unclickable? As users are just allowed to dismiss the prompt, not click on the target view.
Thank you for this interesting library.

**Comment by sjwall** [comment]
Using the [`builder.setAutoDismiss(false)`](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setAutoDismiss-boolean-) and [`builder.setAutoFinish(false)`](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.html#setAutoFinish-boolean-) methods the prompt can then only be dismissed by calling [`prompt.dismiss()`](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.html#dismiss--) or [`prompt.finish()`](https://sjwall.github.io/MaterialTapTargetPrompt/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPrompt.html#finish--). [Checkout the example in the sample.](https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/sample/src/main/java/uk/co/samuelwall/materialtaptargetprompt/sample/MainActivity.java#L273)

Hope this helps, please reopen the issue if more information is needed.
