### ISSUE TITLE
showOverflowPrompt in NavigationView activity

### ISSUE THREAD

**Issue by wangsun6** [sjwall/MaterialTapTargetPrompt#88]
I have used the library in my main activity(navigationView) and its working fine.

but when i try to use in activity(no navigation or empyty activity) showOverflowPrompt function is not working.
"if (child instanceof ActionMenuView)" is returning false, but i have inflated menu:

@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.message_view, menu);
        return true;
    } 

please help me.

### Library Version number
 - 2.4.0

### Operating system and device
 -Android 7.1 Nougat API 25, MI note 4

**Comment by sjwall** [comment]
hmmm it still works for me, there might be something different on the MI note 4. The getChilidAt method isn't really the best way to do it. I shall investigate this further and see if anything has changed that provides a better way to find the overflow view.

**Comment by wangzzzzz** [comment]
(actually wanted to tap-target three vertical dots on top right corner)

i did some try and error method and finally when i used showSideNavigationPrompt i could tap-target three vertical dots(top right corner).

**Comment by mustafa-demir** [comment]
I had similar problem. The main cause is that sometimes we cannot get reference from menu item at the right time. So i changed my code like this and it worked.

```
   @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        if (!getMyApp().getPrefsHelper().getBooleanValue(PrefsHelper.KEY_INTRO_SHOWN, false)) {
            new Handler().post(new Runnable() {
                @Override
                public void run() {
                    menuItemPlay = findViewById(R.id.action_play);
                    showingIntros = true;
                    showIntros();
                }
            });
        }

        return super.onCreateOptionsMenu(menu);
    }
```
