### ISSUE TITLE
Tap Target prompt for action bar menu

### ISSUE THREAD

**Issue by prmacias** [sjwall/MaterialTapTargetPrompt#90]
### Overview
 - Context, problem or idea, solution or next step 

The tap target prompt for action bar menu isn't working. There isn't any error messages in logcat. 

### Reproduction steps

 - Detailed steps to reproduce, how is the Builder being created?

I tried several places to execute this builder below in Activity and Fragment - OnResume(), OnCreate methods. It happens nothing with no message. 

new MaterialTapTargetPrompt.Builder(this)
                .setIcon(R.drawable.ic_action_settings)
                .setTarget(R.id.menu_settings)
                .setPrimaryText("Here is an interesting feature")
                .setSecondaryText("Tap here and you will be surprised")
                .show();

Here is the control (to test other layout to see if it works) and it works.

new MaterialTapTargetPrompt.Builder(getActivity())
                .setTarget(R.id.activity_main_frame_layout)
                .setPrimaryText("Here is an interesting feature")
                .setSecondaryText("Tap here and you will be surprised")
                .show();

Reproduce the issue

### Library Version number

 compile 'uk.co.samuelwall:material-tap-target-prompt:2.4.1'

### Operating system and device

Android 7.1 Nougat API 25, Keyone

**Comment by prmacias** [comment]
I found that the menu will be implemented in onCreateOptionsMenu after the onCreate method so the builder wouldn't know where the target is.

**Comment by sjwall** [comment]
The menu item hasn't been created yet so the findViewById can't find the view. This means that `builder.show()` will return null and `builder.isTargetSet()` will return false. To solve this post a runnable to a new Handler for the main looper thread. The code below is a modified version taken from the MainActivity example.

```java
@Override
public boolean onCreateOptionsMenu(Menu menu)
{
    // Inflate the menu
    getMenuInflater().inflate(R.menu.main, menu);

    new android.os.Handler(Looper.getMainLooper()).post(new Runnable()
    {
        @Override
        public void run()
        {
            // Create the prompt here
            showSearchPrompt(null);
        }
    });

    return true;
}
```

Please reopen this issue if this doesn't solve it for you.
