### ISSUE TITLE
Background color not applied since 2.5.0

### ISSUE THREAD

**Issue by lpellegr** [sjwall/MaterialTapTargetPrompt#94]
I have bumped the dependency to version 2.5.0 from 2.4.1. 

Since this update, the background color for the prompt is no longer applied: it remains transparent.

Here is the result with version 2.4.1:

![mtt-2 4 1](https://user-images.githubusercontent.com/128898/33845134-b679bbae-dea2-11e7-814c-40b3bc4d34a7.png)

Below is the same with version 2.5.0:

![mtt-2 5 0](https://user-images.githubusercontent.com/128898/33845151-c3630e6a-dea2-11e7-91f1-abf10d91a43a.png)

The code used to create the tap target prompt is the same in both cases:

```
new MaterialTapTargetPrompt.Builder(this)
                    .setTarget(left, top)
                    .setIcon(R.drawable.ic_menu_moreoverflow_material_dark)
                    .setBackgroundColour(getResources().getColor(R.color.primary))
                    .setFocalColour(getResources().getColor(R.color.md_white_1000))
                    .setPrimaryText(R.string.onboarding_settings_title)
                    .setSecondaryText(R.string.onboarding_settings_description)
                    .setSecondaryTextColour(getResources().getColor(R.color.translucent_white_tap_target))
                    .setPromptStateChangeListener(new MaterialTapTargetPrompt.PromptStateChangeListener() {
                        @Override
                        public void onPromptStateChanged(MaterialTapTargetPrompt prompt, int state) {
                            mSharedPreferencesHelper.setOnboardingSettings(true);
                        }
                    })
                    .show();
```

The bug was experienced with the Android emulator running API 26.

Is it a bug or due to a change in the API?

**Comment by sjwall** [comment]
This will be a bug, either related to building to android SDK 27 or most likely the fix implement to fix incorrect background size after the target moves in this commit fddc186

I shall investigate it and see if I can reproduce it

**Comment by falary1** [comment]
Same bug for me, not always but really often...

**Comment by sjwall** [comment]
I have been unable to replicate the issue with the emulator I have installed and limited internet connection to download others to test with. I have reverted the changes that I believe have caused this issue and will be releasing this in v2.5.1
