### ISSUE TITLE
How to show prompt in lifecycle function

### ISSUE THREAD

**Issue by saied89** [sjwall/MaterialTapTargetPrompt#98]
Hi
How can I show a prompt on a Toolbar menu item as soon as activity launch?
No matter in which lifecycle callback I put it in show() returns null and nothing happens.

**Comment by sjwall** [comment]
I believe that this has already been answered here: https://github.com/sjwall/MaterialTapTargetPrompt/issues/90#issuecomment-345809738

Please reopen this issue if this doesn't solve it for you.
